docker/src/main/java/org/arquillian/cube/impl/docker/DockerClientExecutor.java, docker/src/test/java/org/arquillian/cube/impl/docker/DockerClientExecutorTest.java
This change request is in relation with issue #68.
One solution is to use regexp.
=> Retrieve docker image id with regexp.

docker/src/main/java/org/arquillian/cube/impl/await/AwaitStrategyFactory.java, docker/src/main/java/org/arquillian/cube/impl/await/SleepingAwaitStrategy.java, docker/src/test/java/org/arquillian/cube/impl/await/AwaitStrategyTest.java
First pull request since quite a lot time. Let me know if there is something wrong.
Regards,
Ralf
=> [#62] Create an static time await

docker-server-stub/pom.xml, docker-server-stub/src/main/java/org/arquillian/cube/docker/stub/ContainerModel.java, docker-server-stub/src/main/java/org/arquillian/cube/docker/stub/SparkServer.java, docker-server-stub/src/test/java/org/arquillian/cube/docker/stub/SparkTest.java, docker/src/main/java/org/arquillian/cube/impl/await/SleepingAwaitStrategy.java, pom.xml
Fix tabs indent and implements docker server stub to be used for testing.
=> Fix tabs indent and implements docker server stub

containerless/pom.xml, docker/pom.xml, docker/src/main/java/org/arquillian/cube/impl/client/CubeExtension.java, ftest-standalone/pom.xml, ftest-standalone/src/test/java/org/arquillian/cube/StandaloneTestCase.java, ftest-standalone/src/test/resources/arquillian.xml, pom.xml
* Add junit-standalone test suite to verify Cube can run
with only junit-standalone present on classpath.
fixes #30
=> Only register container-test integration if available

docker/src/test/java/org/arquillian/cube/impl/client/CubeSuiteLifecycleControllerTest.java, pom.xml
=> Update to Arquillian-Core 1.1.7.Final

docker/src/main/java/org/arquillian/cube/impl/client/CubeConfiguration.java, docker/src/test/java/org/arquillian/cube/impl/client/CubeConfigurationTest.java, docker/src/test/resources/cube
adds default configuration file in case none information is provided. Fixes issue #127
=> adds default configuration file in case none information is provided.

docker/ftest-boot2docker/pom.xml, docker/ftest-boot2docker/src/test/resources/arquillian.xml, docker/ftest-boot2docker/src/test/resources/tomee/Dockerfile, docker/ftest-boot2docker/src/test/resources/tomee/tomcat-users.xml
Adds example of using Apache TomEE with Arquillia Cube.
=> Adds TomEE example

core/src/main/java/org/arquillian/cube/impl/util/SystemEnvironmentVariables.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java
adds DOCKER_HOST env variable to configure DOCKER_HOST server URI. Fixes issue #149
=> adds DOCKER_HOST env variable to configure DOCKER_HOST server URI.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/AutoStartParser.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/AutoStartParserFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CommaSeparatedAutoStartParser.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/RegularExpressionAutoStartParser.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/AutoStartOrderUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeSuiteLifecycleControllerTest.java
resolves issue #161 by adding regular expression support on autostart containers.
=> resolves issue #161 by adding regular expression support on autostart

core/src/main/java/org/arquillian/cube/impl/client/CubeConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/AutomaticResolutionAutoStartParser.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerAutoStartConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerExtension.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/AutoStartOrderUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeRegistrarTestCase.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeSuiteLifecycleControllerTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/util/AutoStartOrderUtilTestCase.java, docker/ftest-docker-machine/docker-compose.yml, docker/ftest-docker-machine/pom.xml, docker/ftest-docker-machine/src/main/java/org/arquillian/cube/servlet/HelloWorldServlet.java, docker/ftest-docker-machine/src/test/java/org/arquillian/cube/servlet/HelloWorldServletTest.java
resolves issue #162 by autostarting containers in case of no autostart strategy
=> resolves issue #162 by autostarting containers in case of no autostart strategy

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java, pom.xml
Print the final docker configuration and update the versions of some dependency
=> resolves issues #169, #184 and #185

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/AutomaticResolutionAutoStartParser.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/AutoStartOrderUtil.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/IOUtil.java, docker/pom.xml
=> Fix several issues

docker/docker/pom.xml, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverter.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/IOUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/simple-cube-system-var.yml
=> Add System Properties resolution in Docker Compose

docker/docker/pom.xml, docker/ftest-docker-containerobject/pom.xml, pom.xml
* Remove ShrinkWrap 1.2.3 override
fixes #269
=> Upgrade to Arquillian Core 1.1.11.Final

README.adoc, docker/docker/pom.xml, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerMachineDistro.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/LatestRepository.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/DockerMachine.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/GitHubUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/util/GitHubUtilTest.java, pom.xml
=> Autodownload Docker Machine

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/Ping.java
=> adds checks for detecting when ping(ss) command is not installed

README.adoc, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainers.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java
allows to use custom cube properties to docker-compose defined containers.
=> allows to use custom cube properties to docker-compose

README.adoc, api/src/main/java/org/arquillian/cube/HostPort.java, core/src/main/java/org/arquillian/cube/impl/client/CubeExtension.java, core/src/main/java/org/arquillian/cube/impl/client/enricher/HostPortTestEnricher.java, core/src/main/java/org/arquillian/cube/impl/model/LocalCubeRegistry.java, core/src/test/java/org/arquillian/cube/impl/client/enricher/HostPortTestEnricherTest.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/PingPongContainer.java, docker/ftest-docker-machine/src/test/java/org/arquillian/cube/servlet/HelloWorldServletTest.java
=> adds HostPort enricher for none container object objects

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
removes ping operation since it is expensive  and a bit useless in our case. Fixes #305
=> removes ping operation since it is expensive 

containerless/pom.xml, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/BindingUtil.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystemFamily.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/YamlUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java, docker/ftest-boot2docker/pom.xml, docker/ftest-docker-compose/pom.xml, docker/ftest-standalone/pom.xml, docker/ftest/pom.xml, pom.xml
=> Upgrade to docker-java 3.0.0-RC1

docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/model/DockerCubeTest.java
See Issue #316 for additional information and background
=> Ignore NotFoundException when stopping/destroying containers

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
Actually when trying to build an image with Arquillian Cube, docker host throwed
the exception message: http: Hijack is incompatible with use of CloseNotifier.
It seems to be a problem with go and should be fixed in go 1.6 (and maybe in
Docker 1.11.0).
For now, closing and recreating the Docker client after a call to the build Docker
command seems to solves the problem.
I let you have a look to the code. If you have a cleaner solution I could write the enhancement.
I'm sorry for the delay…
=> resolves issue #310 by rebuilding dockerClient after a Docker build command

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
Fixes two issue with PR #314:
* clean property is ignored
* fails with exception in case container was already stopped
=> Fixed cleaning on container start

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/DockerMachine.java
=> caught exception in case docker-machine is not invoked successfully

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/ServiceCube.java
Reverts arquillian/arquillian-cube#342
=> Revert "Add a config option "ignoreCleanup" to keep resources when exiting"

README.adoc, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/AwaitStrategyFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/CustomAwaitStrategyInstantiator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/NativeAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/SleepingAwaitStrategyBase.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Await.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/AwaitStrategyTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/CustomAwaitStrategyImpl.java, spi/src/main/java/org/arquillian/cube/spi/await/AwaitStrategy.java
implements issue #338 by adding the possibility to register custom await strategies
=> implements issue #338 by adding the possibility for custom await strategies

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ComposeBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverter.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/NetworkBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/AutomaticResolutionAutostartParser.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/myapp/simple-docker-compose-v2.yml, docker/docker/src/test/resources/simple-docker-compose-networks-v2.yml, docker/docker/src/test/resources/simple-docker-compose-v2.yml, docker/ftest-docker-compose-v2/docker-compose.yml, docker/ftest-docker-compose-v2/envs, docker/ftest-docker-compose-v2/pom.xml, docker/ftest-docker-compose-v2/src/main/java/org/arquillian/cube/servlet/HelloWorldServlet.java, docker/ftest-docker-compose-v2/src/test/java/org/arquillian/cube/servlet/HelloWorldServletTest.java, docker/ftest-docker-compose-v2/src/test/resources/arquillian.launch_file, docker/ftest-docker-compose-v2/src/test/resources/arquillian.xml, docker/ftest-docker-compose-v2/src/test/resources/tomcat/Dockerfile, docker/ftest-docker-compose-v2/src/test/resources/tomcat/tomcat-users.xml, docker/pom.xml
=> Add support to docker-compose.yml version 2

README.adoc, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/DockerCompositions.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/model/DockerCubeTest.java
Add configuration option to remove volumes associated to containers created by Cube when the containers are removed.
=> Add configuration option to remove volumes

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/BindingUtil.java, pom.xml
=> updates docker-java library to latest stable

pom.xml
=> update of jboss-parent to version 21

core/src/main/java/org/arquillian/cube/impl/util/IOUtil.java, core/src/test/java/org/arquillian/cube/impl/util/IOUtilTest.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/metadata/CopyToContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/metadata/ExecuteProcessInContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, pom.xml, spi/src/main/java/org/arquillian/cube/spi/metadata/CanCopyToContainer.java, spi/src/main/java/org/arquillian/cube/spi/metadata/CanExecuteProcessInContainer.java
Adds CopyToContainer and ExecuteProcess operations fixing issue #389
=> Adds CopyToContainer and ExecuteProcess operations

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Link.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java, docs/parallel.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/396)
=> [ISSUE #392] Add star operator

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java
Fixes gh-373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/397)
=> Fix downloading of docker-machine

kubernetes/fabric8/pom.xml, kubernetes/kubernetes/pom.xml, kubernetes/pom.xml, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/398)
=> adds structure for integrating fabric8 kubernetes support

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/test/java/org/arquillian/cube/openshift/test/portfowarder/PortForwarderTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/336)
=> Port-fowarder does not accept you to specify the local port the same as the container.

openshift/openshift/src/main/java/io/undertow/protocols/spdy/SpdyChannelWithoutFlowControl.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwarder.java
This commit Fix: 
java.io.IOException: XNIO000804: Received an invalid message length of -2147287037
After a long running tests (around 1300 in this case) the TCP window gets full leading the client (arquillian) to stop to send data to the server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/347)
=> Port Forwarder Improvements

README.adoc, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeSuiteLifecycleController.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/ExposedPort.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/drone/pom.xml, docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDockerDroneExtension.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDroneConfiguration.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDroneConfigurator.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/DroneOverwriteConfigurator.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/InstallSeleniumCube.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/VncRecorderLifecycleManager.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/util/SeleniumVersionExtractor.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/util/SeleniumVersionUtil.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/util/VolumeCreator.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/util/VolumeUtils.java, docker/drone/src/main/java/org/jboss/arquillian/drone/webdriver/factory/DockerRemoteWebDriverFactory.java, docker/drone/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, docker/drone/src/test/java/org/arquillian/cube/docker/drone/SeleniumContainersTest.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/VncRecorderLifecycleManagerTest.java, docker/ftest-drone/docker-compose.yml, docker/ftest-drone/pom.xml, docker/ftest-drone/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docker/ftest-drone/src/test/resources/arquillian.xml, docker/pom.xml, docs/drone.adoc, pom.xml, spi/src/main/java/org/arquillian/cube/spi/event/lifecycle/BeforeAutoStart.java, spi/src/main/java/org/arquillian/cube/spi/event/lifecycle/BeforeAutoStop.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/402)
=> Adds cube-drone integration. Issue #385

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerExtension.java, docker/drone/pom.xml, docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDockerDroneExtension.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/main/java/org/arquillian/cube/docker/graphene/location/DockerCubeCustomizableURLResourceProvider.java, docker/drone/src/test/java/org/arquillian/cube/docker/graphene/location/CubeDockerCustomizableURLResourceProviderTest.java, docker/ftest-drone/pom.xml, docker/ftest-graphene/docker-compose.yml, docker/ftest-graphene/pom.xml, docker/ftest-graphene/src/test/java/org/arquillian/cube/drone/HomePage.java, docker/ftest-graphene/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docker/ftest-graphene/src/test/resources/arquillian.xml, docker/pom.xml, docs/drone.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/405)
=> Issue #404. Adds Arquillian Graphene support.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDroneConfiguration.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/InstallSeleniumCube.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/SeleniumContainersTest.java, docker/ftest-drone-custom/docker-compose.yml, docker/ftest-drone-custom/pom.xml, docker/ftest-drone-custom/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docker/ftest-drone-custom/src/test/resources/arquillian.xml, docker/ftest-drone-custom/src/test/resources/browser/Dockerfile, docker/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/406)
=> Issue #403. Adds customizable browser images for cube-drone.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/HttpAwaitStrategy.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/420)
=> Each HttpURLConnection instance should be used to make a single request

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/422)
=> Downgrade jboss-parent

api/src/main/java/org/arquillian/cube/CubeIp.java, core/src/main/java/org/arquillian/cube/impl/client/CubeExtension.java, core/src/main/java/org/arquillian/cube/impl/client/enricher/CubeIpTestEnricher.java, core/src/test/java/org/arquillian/cube/impl/client/enricher/CubeIpTestEnricherTest.java, docker/ftest-drone/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docs/enrichers.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/424)
=> [issue #421] adds CubeIp enrichment to inject internal cube ip

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/SinglePortBindResolver.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/util/SinglePortBindResolverTest.java, docker/drone/src/main/java/org/arquillian/cube/docker/graphene/location/DockerCubeCustomizableURLResourceProvider.java, docker/ftest-restassured/docker-compose.yml, docker/ftest-restassured/pom.xml, docker/ftest-restassured/src/test/java/org/arquillian/cube/restassured/PingPongTest.java, docker/ftest-restassured/src/test/resources/arquillian.xml, docker/pom.xml, docker/restassured/pom.xml, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/AuthenticationSchemeFactory.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredConfiguration.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredConfigurator.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredCustomizer.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredExtension.java, docker/restassured/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, docker/restassured/src/test/java/org/arquillian/cube/docker/restassured/AuthenticateSchemeFactoryTest.java, docker/restassured/src/test/java/org/arquillian/cube/docker/restassured/RestAssuredCustomizerTest.java, docs/restassured.adoc, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/427)
=> [issue-416] adds cube docker RestAssured integration

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/SinglePortBindResolver.java, docker/drone/src/main/java/org/arquillian/cube/docker/graphene/location/DockerCubeCustomizableURLResourceProvider.java, docker/drone/src/test/java/org/arquillian/cube/docker/graphene/location/CubeDockerCustomizableURLResourceProviderTest.java
fixes bug by setting internal ip in webdriver  instead of dockerhost
=> [issue #423] ip used in webdriver by graphene is incorrect

docker/docker/src/main/java/org/arquillian/cube/docker/impl/requirement/DockerMachineRequirement.java
This commit check docker machine requirement using `docker-machine ls`
rather than `docker-machine ip`. Also, fix the issue in
ftest-standalone-autostart, which can not start the machine due to the
execution of `docker-machine ip` command before to auto-start the
machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/430)
=> Improve Docker Machine Requirement

README.adoc, docker/ftest-restassured/pom.xml, docker/recorder/pom.xml, docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/CubeDockerRecorderExtension.java, docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/TakeRestAssuredContent.java, docker/restassured/pom.xml, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredConfiguration.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredCustomizer.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredExtension.java, docker/restassured/src/test/java/org/arquillian/cube/docker/restassured/RestAssuredCustomizerTest.java, docs/reports.adoc, docs/restassured.adoc, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/432)
=> [issue #429] integrates restassured to reporter

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docs/configuration.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/433)
=> [issue #391] adds more docker compose operations for cpu and host

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/SinglePortBindResolver.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/util/IpAddressValidator.java, docker/drone/src/main/java/org/arquillian/cube/docker/graphene/location/DockerCubeCustomizableURLResourceProvider.java, docker/drone/src/test/java/org/arquillian/cube/docker/graphene/location/CubeDockerCustomizableURLResourceProviderTest.java, docker/ftest-drone/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docker/ftest-graphene/docker-compose.yml, docker/ftest-graphene/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docs/drone.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/438)
=> issue #437 uses exposed port instead of bind port in Graphene resolution

openshift/openshift/src/main/java/io/undertow/protocols/spdy/SpdyChannelWithoutFlowControl.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwardOpenListener.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwardServerConnection.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwarder.java, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/425)
=> Upgrade to UnderTow 1.3.24.

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/441)
=> [issue #440] Allow user to override local ports for port forwarding

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwardServerConnection.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwarder.java
This is a split of #446.
Once this is merged @spolti can rebase his branch and do another pull request, or force push against #446. He's going to do this anyway, because he will reword and remove some commits.
=> Improvements on Port Forwader

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/Constants.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java
Just like other properties.
Closes #453.
=> k8s: Make namespace prefix fully configurable

core/src/main/java/org/arquillian/cube/impl/util/ConfigUtil.java, core/src/main/java/org/arquillian/cube/impl/util/SystemEnvironmentVariables.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Session.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/Constants.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultSession.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/ShutdownHook.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/TestListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/annotation/AnnotationProviderRegistar.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/await/WaitStrategy.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/label/LabelProviderRegistar.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/locator/KubernetesResourceLocatorRegistar.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/resolve/ShrinkwrapResolver.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/MockTest.java
Most of these stuff were part mentioned in the review of the initial kubernetes pr.
The rest are misc cleaning up and preparation for aligning cube-kubenetes with cube-openshift.
=> Kubernetes cleanup

docker/docker/pom.xml, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ComposeBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverter.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/simple-docker-compose-build-with-context-dir.yml, docker/docker/src/test/resources/simple-docker-compose-build-with-context-git.yml, docker/docker/src/test/resources/simple-docker-compose-build-with-dockerfile.yml, docs/compose.adoc, pom.xml
=> Add support for context in docker-compose v2

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/DockerMachine.java
Fixes NPE when more than one machine is set when one machine fails
=> [issue #478] Fixes NPE when more than one machine 

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/NetworkLifecycleController.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ComposeBuilder.java, docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironment.java, docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java
1. Adds network topology implementation.
2.Resolves null pointer exception for connect to network method.
2.Adds missing logic of networks in composebuilder.
=> Network topology Implementation

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Session.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/SessionListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultSession.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesExtension.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionCreatedEvent.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionCreatedListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SuiteListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/event/Start.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/event/Stop.java
This is more like a check to see if CircleCI is working.
=> Allow session listeners to be registered with the session on runtime.

docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java
Fixes issue_498 by adding Cube format in parameters
=> Fix [issue #498]

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/IPAM.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Network.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ComposeBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/NetworkBuilder.java, docker/ftest-docker-machine-network/docker-compose.yml, docker/ftest-docker-machine-network/src/test/java/org/arquillian/cube/servlet/PingPongTest.java
- Adds ipam support for network
- Added ipam support
- Added driver_opts support
- You can assign static ip Address using docker-compose v2.
**Fixes**: #484
=> [Issue #484]Implements network ipam support. 

docker/assertj/pom.xml, docker/assertj/src/main/java/com/github/dockerjava/assertions/ContainerAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/ContainerStateAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/ContainersAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/DockerJavaAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/DockerJavaAssertions.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/ImagesAssert.java, docker/assertj/src/test/groovy/com/github/dockerjava/assertions/DockerJavaAssertionsSpec.groovy, docker/pom.xml
Custom assertions for docker-java project.
- Assertions for images
- Assertions for containers
**Fixes**: #461
=> Add assertj module

kubernetes/ftest-kubernetes-reporter/pom.xml, kubernetes/ftest-kubernetes-reporter/src/test/java/HelloWorldTest.java, kubernetes/ftest-kubernetes-reporter/src/test/resources/arquillian.xml, kubernetes/ftest-kubernetes-reporter/src/test/resources/kubernetes.json, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionCreatedListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/event/AfterStart.java, kubernetes/pom.xml, kubernetes/reporter/pom.xml, kubernetes/reporter/src/main/java/org/arquillian/cube/kubernetes/reporter/KubernetesReporterExtension.java, kubernetes/reporter/src/main/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformation.java, kubernetes/reporter/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, kubernetes/reporter/src/test/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformationTest.java, kubernetes/reporter/src/test/resources/kubernetes.json, pom.xml
Implements Reporter integration with cube kubernetes
Adds kubernetes reporter 
- To report config file.
- To report dynamic properties of session - namespace, pods, rc, services etc.
**Fixes**: #536
=> Adds kubernetes reporter integration.

docs/kubernetes.adoc, docs/reports.adoc
Updated document for kubernetes reporter integration.
=> Kubernetes reporter integration documentation

core/pom.xml, core/src/main/java/org/arquillian/cube/impl/client/container/remote/CubeAuxiliaryArchiveAppender.java
Adds required classes to run ArquillianConditionalRunner if we run tests as incontainer tests.
**Fixes**: #527
=> Adds requirements classes if tests running as in-container.

docker/ftest-docker-compose-v2/docker-compose.yml, docker/ftest-docker-compose-v2/src/test/java/org/arquillian/cube/servlet/HelloWorldServletTest.java, docker/ftest-docker-compose-v2/src/test/resources/arquillian.launch_file, docker/ftest-docker-compose-v2/src/test/resources/tomcat/Dockerfile, docker/ftest-docker-compose/docker-compose.yml, docker/ftest-docker-compose/src/test/java/org/arquillian/cube/servlet/HelloWorldServletTest.java, docker/ftest-docker-compose/src/test/resources/arquillian.launch_file, docker/ftest-docker-compose/src/test/resources/tomcat/Dockerfile
Fixed failing tests for docker-compose.
- tomcat docker image is using jre8
**Fixes**: #548
=> Fixed failing functional tests for compose.

docker/ftest-docker-compose-v2/envs, docker/ftest-docker-compose/envs
Removed unwanted env property.
- Removed unwanted env property after changing docker image to dockerhub.
=> removed unwanted env property.

api/src/main/java/org/arquillian/cube/containerobject/Cube.java, api/src/main/java/org/arquillian/cube/containerobject/Environment.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/ContainerObjectUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/util/ContainerObjectUtilTest.java, docker/ftest-docker-containerobject/pom.xml, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpClient.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpClientTest.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpContainer.java, docs/cop.adoc
Fix bugs in Container object pattern and update examples
**Fixes**: #554
=> Fix bugs in Container object pattern and update examples

api/src/main/java/org/arquillian/cube/containerobject/Volume.java, api/src/main/java/org/arquillian/cube/containerobject/Volumes.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/ContainerObjectUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricherTest.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/PingPongContainer.java, docs/cop.adoc
Adds `@Volume` annotation in container object so you can define volumes in container objects too.
- Adds `@Volume` annotation
**Fixes**: #559
=> Adds @Volume annotation

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java
Adds ```@CubeIp``` annotation support for Container objects
- Modified ```CubeContainerObjectTestEnricher``` to enrich container objects with fields annotated with ```@CubeIp```
**Fixes**: #562
=> adds support for enriching container objects with CubeIp annotations (#562)

docker/assertj/src/main/java/com/github/dockerjava/CubeOutput.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/ContainerAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/CubeOutputAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/DockerJavaAssert.java
Adds assertJ matcher for container processes.
**Fixes**: #572
=> Adds AssertJ Matcher hasProcessRunning.

docker/assertj/src/main/java/com/github/dockerjava/assertions/CubeOutputAssert.java
Adds SoftAssertions & custom messages to assertJ
=> Adds minor improvement to Custom AssertJ Matcher.

docs/kubernetes.adoc
=> minor spelling mistakes.

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/ResourceInstaller.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesExtension.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManagerLifecycle.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/TestListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/enricher/KuberntesServiceUrlResourceProvider.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/install/DefaultResourceInstaller.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/install/ResourceInstallerRegistar.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/GitServer.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClient.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/install/OpenshiftResourceInstaller.java, pom.xml
This pull requests fixes some things that have been broken in the openshift extension.
=> Openshift improvements

pom.xml
2.1.0 has some fixes related to readiness checks and more.
=> Bump kubernetes-client to 2.1.0.

docker/assertj/src/main/java/com/github/dockerjava/assertions/DockerJavaAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/VersionAssert.java, docker/assertj/src/test/groovy/com/github/dockerjava/assertions/DockerJavaAssertionsSpec.groovy, docker/assertj/src/test/resources/version.json, docker/assertj/src/test/resources/version_experimental_false.json
Add new asserts for assertj-docker-java module
- New asserts to version api
**Fixes**: #
=> Add new asserts for version api

docker/assertj/src/main/java/com/github/dockerjava/assertions/ContainerAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/DockerJavaAssert.java, docker/assertj/src/main/java/com/github/dockerjava/assertions/ImageAssert.java, docker/assertj/src/test/groovy/com/github/dockerjava/assertions/DockerJavaAssertionsSpec.groovy, docker/assertj/src/test/resources/container.json, docker/assertj/src/test/resources/image.json
Add new asserts for labels in assertj-docker-java module
* Support for image's labels
* Support for container's labels
**Fixes**: #
=> Add new asserts for labels

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java
Fallback to Ping strategy in case of previous failures.
- If `sscommand` and `waitforit` strategies fails, then it relies to Ping.
-
-
**Fixes**: #598
=> Fallback to Ping strategy in case of previous failures.

pom.xml
=> Bump kubernetes-client to 2.2.0.

README.adoc, docs/forge.adoc
Added documentation for Arquillian addon for forge integration with cube.
=> Adds documents for forge cube.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Image.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/config/ImageParserTest.java
Sets Remote URL at connection level instead of pull
-
-
-
**Fixes**: #632
=> Sets Remote URL at connection level instead of pull

kubernetes/ftest-kubernetes/src/test/java/HelloWorldTest.java
This pull request modifies an existing unit test so that we test against the case mentioned in #641.
=> 641: Access the forwarded port multiple times.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java
Add Volume binding when volumes is specified
- When volumes are used in containers, binding volumes are configured automatically as well.
**Fixes**: #649
=> Add Volume binding when volumes is specified

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/locator/DefaultKubernetesResourceLocator.java
Resolves stackoverflow for .yaml configuration file
**Fixes**: #653
=> Resolves stackoverflow error.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/beforeStop/BeforeStopActionFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/beforeStop/CustomBeforeStopActionInstantiator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/BeforeStopContainerObserver.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/beforeStop/BeforeStopActionTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/beforeStop/CustomBeforeStopActionImpl.java, docs/configuration.adoc
For this  pull request, please see issue https://github.com/arquillian/arquillian-cube/issues/671 
- Use cubeId for providing custom strategies
- Updated docuemtation and tests
**Fixes**: #
Issue 671
=> Issue 671 use cube id for custom strategies

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java
Resolving issue #676. 
I have taken steps described by @lordofthejars and verified that the change works.
=> Resolve qouted docker-compose command

docker/ftest-docker-junit-rule/pom.xml, docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/RedisTest.java, docker/junit-rule/pom.xml, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/ContainerDslRule.java, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/Reflections.java, docker/pom.xml, docs/cop.adoc, pom.xml
Adds JUnit rule support for Container Object DSL
- Adds JUnit rule
-
-
**Fixes**: #678
=> Adds JUnit rule support for Container Object DSL

docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/ContainerDslRule.java
Adds Dockerfile support for Container Object DSL
**Fixes**: #686
=> Adds Dockerfile support for Container Object DSL

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/Container.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/NetworkTest.java, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/ContainerDslRule.java, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/DockerClientInitializer.java, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/NetworkDslRule.java, docs/cop.adoc
Adds Network DSL for JUnit Rule
**Fixes**: #688
=> Adds Network DSL for JUnit Rule

bom/pom.xml, docs/bom.adoc
=> * Modifies bom to import jars for all cube dependencies

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/LogScanningAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Await.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/AwaitBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/AwaitStrategyTest.java, docs/configuration.adoc
=> Adds occurrences parameter in await log strategy

core/src/main/java/org/arquillian/cube/impl/util/ReflectionUtil.java
=> Fixed infinite loop

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/StarOperator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/ContainerBuilder.java, docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/RedisTest.java
Adds star operator support in Container Object DSL
- Star operator logic is implemented when Container Object Build process is called
**Fixes**: #698
=> feat(#698) Adds star operator support in Container Object DSL

docker/docker/src/main/resources/org/arquillian/cube/docker/impl/await/wait-for-it-sh.sh
Updates to latest `wait-for-it` script
**Fixes**: #700
=> fix(#700): Updates to latest wait-for-it script

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/feedback/DefaultFeedbackProvider.java
Currently, displaying events doesn't work. This pr fixes that.
=> Improve events handling in the DefaultFeedbackProvider.

docker/assertj/src/test/groovy/com/github/dockerjava/assertions/DockerJavaAssertionsSpec.groovy, pom.xml
Update to latest assertj and fix error messages
- Update to assertj 3.8.0
- Fix expected failing message
**Fixes**: #695
=> fix(test): Update to latest assertj and fix error messages

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java
Follows up #719 and complete #704.
=> OSFUSE-175: Better existing project check for basic user

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/ServiceCube.java
=> Openshift: Consider the cleanup flag when destroying pods/services

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/portforward/PortForwardServerConnection.java
Details: https://github.com/arquillian/arquillian-cube/issues/752
Fixes #752
=> Hanging connections on PortForwarder

docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpClient.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpClientTest.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpContainer.java
=> Fixed failing tests due to incorrect usage of ftpclient

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
=> Add support for private Docker registry to build command

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfigurationFactory.java
=> Capitalize S from CubeOpenshiftConfigurationFactory class

docs/enrichers.adoc, docs/kubernetes.adoc
=> Improve RouteURL doc

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/portforward/PortForwardServerConnection.java
Complementary of 67438642 (Make sure to release the error channel latch)
=> PortForwarder: Make sure to release the request channel latch

docs/kubernetes.adoc, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
Adds flag to control when Image Stream files should be processed
- Adds `enableImageStreamDetection` flag
**Fixes**: #795
=> feat(#795): Adds flag to control Image Stream detection

docs/enrichers.adoc
This is a docs follow-up to #803.
=> update docs for recent @RouteURL change

core/src/main/java/org/arquillian/cube/impl/util/ConfigUtil.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java
=> fix config value lookup ordering

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
It would allow for such route injection
```
@RouteURL("${project.artifactId}")
private String route;
```
- allow for route value (system) properties replacement
- inject other route types then just URL; URI and String
Fixes #
routeURL null check
=> Apply replace on route value. Handle route injection type.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/StarOperator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/ContainerBuilder.java, docs/parallel.adoc
Make Star Operator compatible with depends_on
- Adjust container names below depends_on when using star operator.
Fixes #845
=> Star operator compatibility with depends_on

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CECubeInitializer.java
It was missing from ce-arq migration.
=> Inject ConfigurationHandle object

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
=> feat(#867): provide an option to skip readiness await

openshift/ftest-standalone/pom.xml, openshift/ftest-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldTest.java, pom.xml
=> fix(#869): update core to latest & remove unnecessary dependencies.

docs/kubernetes.adoc, kubernetes/kubernetes/pom.xml, openshift/ftest-openshift-assistant/pom.xml, openshift/ftest-openshift-assistant/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftAssistantTest.java, openshift/ftest-openshift-assistant/src/test/resources/arquillian.xml, openshift/ftest-openshift-assistant/src/test/resources/hello-route.json, openshift/ftest-openshift-assistant/src/test/resources/openshift.json, openshift/openshift/pom.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CEEnvironmentProcessor.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistant.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistantCreator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistantDefaultResourcesLocator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClient.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/external/OpenShiftAssistantResourceProvider.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/external/OpenshiftClientResourceProvider.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/ext/TemplateContainerStarter.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/fabric8/F8OpenShiftAdapter.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/utils/TemplateUtils.java, openshift/pom.xml, pom.xml
Adds OpenShift assistant class to deploy programmatically
- Creates OpenShift Assistant enricher
- Removes unnecessary dependencies
Fixes #889
=> feat(#889): Adds OpenShift assistant class to deploy programmatically

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java
=> fix: ConcurrentModificationException when clearing console listener.

docker/ftest-system-properties/pom.xml
- Removes Duplicated dependency
=> Removes duplicated dependency

docker/restassured/src/test/java/org/arquillian/cube/docker/restassured/AuthenticateSchemeFactoryTest.java, pom.xml
In addition one change was required for Rest Assured as they modified return types in the API
=> chore(deps): updates dependencies

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricherTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilderTest.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java
With this VNC container can start on Selinux machine
- Enabling `Z` flag for docker volume 
Fixes #907
=> Permission fix for Selinux

docker/ftest-junit-rules/pom.xml, docker/ftest-junit-rules/src/test/java/org/arquillian/cube/StandaloneJUnitRulesTestCase.java, docker/ftest-junit-rules/src/test/resources/arquillian.xml, docker/pom.xml, pom.xml
Adds example for new JUnit arquillian Rule implemented as a part of arquillian/arquillian-core#147.
Fixes #912
=> Adds example for new JUnit Rules

bom/pom.xml
=> Add arquillian-cube-openshift-shrinkwrap to the bom

pom.xml
Update to Kubernetes 3.1.7
Fixes: #923
=> chore(#923): Update to kubernetes 3.1.7

docs/configuration.adoc
This is a very useful feature when using parallelized cubes with
networks. Only spotted it by digging in code.
=> Add doc for alias

pom.xml
This is needed for https://issues.jboss.org/browse/SB-427.
=> Upgrade to k8s-client 3.1.8

docs/kubernetes.adoc
Fixes wrong reference to PingPongTest in docs.
Fixes #954
=> fix(#954): wrong ref to test example in doc.

docs/forge.adoc, docs/kubernetes.adoc, openshift/ftest-template-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldTemplateIT.java, openshift/ftest-template-standalone/src/test/resources/hello-openshift.yaml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CEEnvironmentProcessor.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/utils/Strings.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/utils/TemplateUtils.java
- supporting templates from classpath
- few documentation fixes
Fixes #949
=> feat(#949): supporting templates from classpath

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java
Adds logging information in important case while creating namespace logic
Fixes #979
=> fix(#979): Adds logging information 

.travis.yml, foo.sh, nsetter_and_systemd_run_setup.sh
- Adds oc version 3.7.0 an 3.7.1
Fixes #978
=> fix(#978): Adds openshift cluster 3.7.0 and 3.7.1 in CI

docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/model/DockerCubeTest.java
- Allow DockerCube to create docker container if it's destroyed
Fixes #988
=> fix(#988): creating container if it has destroyed state

openshift/ftest-template-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldTemplatesIT.java, openshift/ftest-template-standalone/src/test/resources/hello-openshift-templates.yaml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/resources/TemplateProcessor.java
- Replace `Collections.copy()` with `list.addAll()`
- Adds ftest 
-
Fixes #998
=> fix(#998): fixes collections.copy() for templateProcessor

.travis.yml, .travis/nsetter_and_systemd_run_setup.sh
=> fix(#1022): fix nsenter and update to latest version of oc

openshift/ftest-oc-proxy/src/test/java/org/arquillian/cube/openshift/ftest/HelloWorldIT.java
=> fix(#1029): update test to work with kubectl v1.10.0

.travis.yml
=> fix(#1031): drop oc v3.7.1 for CI

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/install/DefaultResourceInstaller.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java
* Removes obsolete code
* Simplified method
=> chore: removes obsolete code

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
=> fix(#1018): refactor toString() for DefaultConfiguration and CubeOpenShiftConfiguration

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java
=> fix: use String.format correctly

docs/fabric8.adoc
Updated fabric8-maven-plugin  example link to use from latest master
=> docs: update link to use from arquillian master

core/src/main/java/org/arquillian/cube/impl/client/CubeExtension.java, core/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java, core/src/main/java/org/arquillian/cube/impl/client/container/ContainerMetadataUpdater.java, core/src/main/java/org/arquillian/cube/impl/model/ContainerMetadata.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/StarOperator.java, docker/ftest-container-star-operator/pom.xml, docker/ftest-container-star-operator/src/main/java/org/arquillian/cube/servlet/HelloWorldServlet.java, docker/ftest-container-star-operator/src/test/java/org/arquillian/cube/servlet/HelloWorldServletIT.java, docker/ftest-container-star-operator/src/test/resources/arquillian.xml, docker/ftest-container-star-operator/src/test/resources/wildfly/Dockerfile, docker/pom.xml, openshift/ftest-standalone/src/test/java/org/arquillian/cube/openshift/standalone/FooTest.java
=> fix(#828): uses random port for port binding for container mode

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/resolver/ResourceResolver.java
This proposal uses a temporary file workaround for the #1045 issue.
Fixes #1045
=> Make @OpenShiftResource annotation work again with plain text

.travis.yml, docs/enrichers.adoc, openshift/ftest-openshift-routeurl/pom.xml, openshift/ftest-openshift-routeurl/src/test/java/org/arquillian/cube/openshift/routeurl/RouteInOtherNamespaceIT.java, openshift/ftest-openshift-routeurl/src/test/resources/arquillian.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURL.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java, openshift/pom.xml
=> Add the ability to inject a URL from a Route in an arbitrary namespace

docs/kubernetes.adoc, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/ResourceUtil.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/AwaitRoute.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
=> feat(#1065): provide an option to repeat @AwaitRoute several times

docs/kubernetes.adoc, kubernetes/istio/istio-api/src/main/java/org/arquillian/cube/istio/api/IstioResource.java, kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioResourcesApplier.java, openshift/ftest-istio-openshift/src/test/java/org/arquillian/cube/openshift/standalone/AbstractReviewsTest.java, openshift/ftest-istio-openshift/src/test/java/org/arquillian/cube/openshift/standalone/ReviewsIstioSourceOnMethodIT.java
=> Enable setting IstioResource on test methods in addition to test class

pom.xml
=> Bump istio-java-api to 0.12

kubernetes/istio/istio-api/src/main/java/org/arquillian/cube/istio/api/RestoreIstioResource.java, kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioResourcesApplier.java, kubernetes/istio/istio/src/test/java/org/arquillian/cube/istio/impl/IstioResourcesApplierTest.java, kubernetes/istio/istio/src/test/resources/virtual-service.yml, pom.xml
Implementation of RestoreIstioResource
Fixes #1094
=> Implementation of RestoreIstioResource

docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java
Expose VNC port on debug images
- Expose VNC port 5900 on debug images
Fixes #1103
=> Fix #1103 Expose VNC

.travis.yml
=> fix: travis CI build uses openjdk8

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/reporter/src/main/java/org/arquillian/cube/docker/impl/client/reporter/ContainerStatsBuilder.java, docker/reporter/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java, pom.xml
=> chore(deps): bumps docker-java to 3.1.5

.travis.yml, README.adoc, docs/compose.adoc, docs/drone.adoc, docs/fabric8.adoc, docs/reports.adoc, docs/restassured.adoc
Fix #1277 
---
**Draft for testing purposes**
Let's see how the CI checks run
Renaming the `master` branch to main
- Renaming the `master` branch to main
Fixes #
=> [issue-1277] - Rename master -> main

.github/dependabot.yml
Clone of #1187 for main
- SSIA
Fixes #1273
=> Create dependabot.yml to enable dependantbot v2 version updates

README.adoc, docs/build-containers.adoc, docs/compose.adoc, docs/configuration.adoc, docs/drone.adoc, docs/enrichers.adoc, docs/requirements.adoc, docs/restassured.adoc, docs/what-is-this.adoc
Fixing post-merge review comments, see https://github.com/arquillian/arquillian-cube/pull/1345#pullrequestreview-2551658914
- Removing docker machine mentions from the documentation
Fixes #1344
=> [issue-1344] - More fixes to the project documentation for 2.0.0 release

bom/pom.xml, pom.xml
Updating the `maven-release-plugin` configuration to align with arquillian-core 
- Update the plugin config in pom.xml
- Update the plugin config in bom/pom.xml
Resolves #1349
=> [issue-1349] - Update the maven-release-release plugin config

build/docs/pom.xml, build/pom.xml
SSIA
- Fix the version in `build` module and submodule POMs
Fixes #
=> Fix the build module (and submodule) POM coordinates

.github/workflows/deploy-docs.yml, README.adoc
SSIA
- Update README.adoc
- Update the GitHub workflow that delivers documentation
Fixes #
=> Update documentation to 2.0.0.Final

.github/workflows/maven.yml, docker/assertj/pom.xml, openshift/ftest-containerless/pom.xml, pom.xml
Support modular JDK (JDK 17 ATM)
- introduce modular JDK client options
- bump some dependencies' verison to work with JDK 17
Resolves #1358
=> [issue-1358] - Support modular JDK

.github/workflows/e2e-tests.yml, jkube-maven-plugin-build/src/main/java/org/eclipse/jkube/maven/plugin/build/JKubeMavenPluginResourceGeneratorBuilder.java, jkube-maven-plugin-build/src/test/java/org/fabric8/maven/plugin/build/KubernetesResourceGeneratorBuilderIT.java, kubernetes/ftest-kubernetes-assistant/pom.xml, kubernetes/ftest-kubernetes-wildfly-bootable-jar/pom.xml, kubernetes/ftest-kubernetes-wildfly-bootable-jar/src/main/java/org/arquillian/cube/kubernetes/HelloWorldEndpoint.java, kubernetes/ftest-kubernetes-wildfly-bootable-jar/src/main/java/org/arquillian/cube/kubernetes/RestApplication.java, kubernetes/ftest-kubernetes-wildfly-bootable-jar/src/test/java/org/arquillian/cube/kubernetes/WildflyBootableJarKubernetesIT.java, kubernetes/ftest-kubernetes-wildfly-bootable-jar/src/test/resources/arquillian.xml, kubernetes/ftest-kubernetes-wildfly-bootable-jar/src/test/resources/hello-world-ingress.yaml, kubernetes/pom.xml, openshift/ftest-openshift-assistant-operational-methods/pom.xml, openshift/ftest-openshift-assistant-template/pom.xml, openshift/ftest-openshift-assistant/pom.xml, openshift/ftest-openshift-resources-standalone/pom.xml, openshift/ftest-openshift-routeurl/pom.xml, pom.xml
SSIA
- Add a WildFly test for Kubernetes, using the Arquillian Cube JKube integration
Fixes #1365
=> Wildfly + JKube on Kubernetes example

.github/workflows/e2e-tests.yml, docker/docker/pom.xml, docker/docker/src/main/java/org/arquillian/cube/docker/impl/requirement/DockerRequirement.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/requirement/DockerRequirementTest.java, kubernetes/ftest-kubernetes-wildfly-bootable-jar/pom.xml, kubernetes/ftest-kubernetes-wildfly-bootable-jar/src/test/java/org/arquillian/cube/kubernetes/WildflyBootableJarKubernetesIT.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/PortForwarderTest.java, kubernetes/pom.xml, openshift/ftest-openshift-wildfly-bootable-jar/pom.xml, openshift/ftest-openshift-wildfly-bootable-jar/src/main/java/org/arquillian/cube/kubernetes/HelloWorldEndpoint.java, openshift/ftest-openshift-wildfly-bootable-jar/src/main/java/org/arquillian/cube/kubernetes/RestApplication.java, openshift/ftest-openshift-wildfly-bootable-jar/src/test/java/org/arquillian/cube/kubernetes/WildflyBootableJarOpenShiftIT.java, openshift/ftest-openshift-wildfly-bootable-jar/src/test/resources/arquillian.xml, openshift/pom.xml
SSIA
- A new functional test to verify how a modern WildFly Bootable JAR can be deployed and tested on OpenShift 
- A fix to the WildFly Bootable JAR k8s test artifact id
Fixes #1374
=> Adding a new WildFly Bootable JAR on OpenShift test

CONTRIBUTING.adoc, dco.txt
Adding a CONTRIBUTING.adoc file.
Fixes #1403
=> [issue-1403] - Adding CONTRIBUTING.adoc

CODE_OF_CONDUCT.adoc
Adding a CODE_OF_CONDUCT.md file
See above.
Fixes #1401
=> [issue-1401] - Adding CODE_OF_CONDUCT.adoc
