arquillian/arquillian-cube

docker/src/main/java/org/arquillian/cube/impl/client/container/RemapContainerController.java, spi/src/main/java/org/arquillian/cube/spi/Binding.java
Resolves issue #66 by not trying to remap ports when no port binding. Probably this means that port binding is dynamically assigned by docker server.
=> resolves issue #66

docker/pom.xml, docker/src/test/java/org/arquillian/cube/impl/await/AwaitStrategyTest.java, pom.xml
Move to depend on mockito-core instead of mockito-all as
mockito-all bundle hamcrast 1.1 which conflcits with junit 4.11
hamcrast version 1.3 causing NoSuchMethod exceptions.
=> Update AwaitStrategyTest to check for correct default value

docker/src/main/java/org/arquillian/cube/impl/client/CubeSuiteLifecycleController.java, docker/src/main/java/org/arquillian/cube/impl/util/AutoStartOrderUtil.java, docker/src/test/java/org/arquillian/cube/impl/client/CubeSuiteLifecycleControllerTest.java, docker/src/test/java/org/arquillian/cube/impl/util/AutoStartOrderUtilTestCase.java
Cubes configured for auto start will now be sorted and
executed in correct start up order based on the
defined links in the configuration.
When linked levels are defined, A->B->C, the parallel execution
will occure in steps per link.
If A->B:
* then no real parallel can be done since B needs to be
started before A
If A->B and C->B
* then B will be started, so A and C in parallel.
If A and B (no link)
* then A and B will be started in parallel
If A->B and autoStartContainers= A
* then B will also be started since it's required by A
fixes #73
=> Add support for auto starting Cubes in parallel

docker/src/main/java/org/arquillian/cube/impl/client/ConnectionMode.java, docker/src/main/java/org/arquillian/cube/impl/client/CubeConfiguration.java, docker/src/main/java/org/arquillian/cube/impl/client/CubeSuiteLifecycleController.java, docker/src/main/java/org/arquillian/cube/impl/client/container/CubeContainerLifecycleController.java, docker/src/main/java/org/arquillian/cube/impl/docker/DockerClientExecutor.java, docker/src/test/java/org/arquillian/cube/impl/client/CubeSuiteLifecycleControllerTest.java, docker/src/test/java/org/arquillian/cube/impl/client/container/CubeContainerLifecycleControllerTest.java, pom.xml
resolves issue #110 by adding connection mode attribute for reusing already existing containers.
=> resolves issue #110 by adding connection mode

docker/src/main/java/org/arquillian/cube/impl/client/CubeClientCreator.java, docker/src/main/java/org/arquillian/cube/impl/client/CubeConfiguration.java, docker/src/main/java/org/arquillian/cube/impl/client/CubeConfigurator.java, docker/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java, docker/src/main/java/org/arquillian/cube/impl/docker/DockerClientExecutor.java, docker/src/main/java/org/arquillian/cube/impl/util/BindingUtil.java, docker/src/main/java/org/arquillian/cube/impl/util/Boot2Docker.java, docker/src/test/java/org/arquillian/cube/impl/docker/DockerClientExecutorTest.java, ftest-boot2docker/pom.xml
adds dockerServerIp substitutions instead of boot2docker in container configuration and env section.
=> adds dockerServerIp substitutions instead of boot2docker

containerless/pom.xml, containerless/src/main/java/org/arquillian/cube/impl/containerless/ContainerlessDockerDeployableContainer.java, containerless/src/main/java/org/arquillian/cube/impl/containerless/IOUtil.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/IOUtil.java
Containerless Container is reusable between Cube Docker
and Cube OpenShift.
* Add support for Servlet Protocol discovery and 'fake'
mapping of ServletTestRunner in ProtocolMetadata. This allow
for in container testing of prepared Docker images.
=> Remove dependency on Cube Docker

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/IOUtil.java
The pull request proposes to use the ``IOUtils.LINE_SEPARATOR_UNIX`` constant from ``commons-io`` (already available in the module) to specify line ending.
=> resolves issue #181 by forcing a Unix EOL instead of a platform dependant one

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/BindingUtil.java
In this scenario boundPort is set to -1.
fixes #208 
I updated the 'ping' polling option to take the -1 boundPort into account. Not sure if there are other places we need to handle this as well?
=> Return ContainerConfig exposedPorts if no HostConfig boundPorts found

docker/docker/pom.xml, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/simple-cube-var.yml
The DockerComposeConverterTest expects that an image name in the docker-compose.yaml is correctly replaced with the content of an environment variable.
Unfortunately the env var `USER` is not available on Windows, so that the test fails.
(`USER` is probably chosen as an arbitrary image name without any further purpose.)
Fixed by explicitly setting the env variable `TESTIMAGENAME` in the configuration of the surefire plugin and using this in the yaml file.
Additionally fixed a typo in a private method name that appears in log messages (`logUsupportedOperations`)
=> Fix DockerComposeConverterTest when building on Windows.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java
fixes #217 
Technically we could make some kind of property->config name map and interate over it to simplify fromMap and toString, but this should fix the issue for now.
=> Use external configuration names when printing configuration options

docker/docker/pom.xml
docker-server-stub artifact no longer exist.
See gh-239
=> Remove docker-server-stub dependency

core/src/main/java/org/arquillian/cube/impl/client/ClientCubeController.java, core/src/main/java/org/arquillian/cube/impl/model/LocalCubeRegistry.java, core/src/test/java/org/arquillian/cube/impl/client/CubeMetadataTest.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/metadata/ChangesOnFilesystem.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/metadata/CopyFromContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/metadata/GetTop.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/ServiceCube.java, spi/src/main/java/org/arquillian/cube/spi/BaseCube.java, spi/src/main/java/org/arquillian/cube/spi/Cube.java, spi/src/main/java/org/arquillian/cube/spi/CubeRegistry.java, spi/src/main/java/org/arquillian/cube/spi/metadata/CanCopyFromContainer.java, spi/src/main/java/org/arquillian/cube/spi/metadata/CanSeeChangesOnFilesystem.java, spi/src/main/java/org/arquillian/cube/spi/metadata/CanSeeTop.java, spi/src/main/java/org/arquillian/cube/spi/metadata/CubeMetadata.java, spi/src/main/java/org/arquillian/cube/spi/metadata/IsBuildable.java, spi/src/main/java/org/arquillian/cube/spi/metadata/IsContainerObject.java
* Introduce CubeMetadata interface to bind all Metadata objects
Update Cube interface:
<X extends CubeMetadata> boolean hasMetadata(Class<X> type);
<X extends CubeMetadata> void addMetadata(Class<X> type, X impl);
<X extends CubeMetadata> X getMetadata(Class<X> type);
Move the following methods from the Cube interface:
* copyFileDirectoryFromContainer
* changesOnFilesystem
* copyLog
* top
To the new Metadata objects:
* CanCopyFileDirectoryFromContainer (impl CopyFileDirectoryFromContainer)
* CanSeeChangesOnFilesystem (impl ChangesOnFilesystem)
* CanCopyLog (impl CopyLog)
* CanSeeTop (impl GetTop)
fixes #246
fixes #247
=> Move special Cube methods to Metadata Objects

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/AwaitStrategyTest.java
In some cases the Container might bind ports that are not
listened to by the started process during startup.
Allow PollingStrategy to take a list of Ports to override
the configured ports.
=> Add support for predefined Polling ports

core/src/test/java/org/arquillian/cube/impl/util/TestPortBindings.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/BindingUtil.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/ServiceCube.java, spi/src/main/java/org/arquillian/cube/spi/Binding.java, spi/src/main/java/org/arquillian/cube/spi/metadata/HasPortBindings.java
Allow to see options for Container to Container communication from the client
side.
=> Expose Container internal IP in HasPortBindings

docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerMachineDistro.java
From version 0.5.6 to 0.6.0, distribution packages have changed.
See gh-296
=> Update distro names

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
@lordofthejars @aslakknutsen 
this works for me, both for machine and natively, could you test boot2docker?
It is true by default. That means that you do not need to set this when you are on Mac or Windows. In case you are on Linux, you would have to explicitly set it to false.
There are not tests for it. It would be cool if you could add them where necessary. I do not know how to deal with it.
=> introduction of dockerTlsVerify property

README.adoc, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java
With upgraded to docker-java 3.0.0-RC3 (PR #295) Cube doesn't accept `http://` and `https://` in `serverUri` parameter anymore. PR #325 added `tlsVerify` parameter but value set by user in arquillian.xml file is overwritten via automatic resolution. The net result is that you can't connect to remote Docker host without TLS.
This PR brings back http and https scheme support and allow manual setting of tlsVerify attribute as well. (Of course tcp and unix schemes remain supported.)
In case the serverUri has http or https scheme, the tlsVerify attribute is set automatically to false or true respectively. Also the URI schema is changed to `tcp://` to make docker-java happy.
=> Restore ability to connect Docker server without TLS

README.adoc, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/AwaitStrategyFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/LogScanningAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/SleepingAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/SleepingAwaitStrategyBase.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/StaticAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Await.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/Ping.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/PingCommand.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/AwaitStrategyTest.java
Initial implementation of a new await strategy that scans the container log for specified pattern to detect service startup. The pattern is matched to every log line. It can be a plain text or regular expression.
This strategy can be used when there is no port to ping or connect to the port successfully doesn't mean the service is fully initialized.
I've tested it only on Windows but it should work on other platforms too.
I don't know if this is sound enough to be included in Cube. I just wanted to show the idea. Any criticism are welcomed. :smile:
=> Add log scanning await strategy

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/ServiceCube.java
Sometimes, mainly when debugging, it's useful to keep pods around
in order to take a closer look at them, their logs, their state, etc.
=> Add a config option "ignoreCleanup" to keep resources when exiting

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/GitServer.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClient.java, pom.xml
Changed KubernetesClient to NamespacedKubernetesClient
And OpenShiftClient to NamespacedOpenShiftClient
Because new k8s api changed the interfaces that carry
methods like inNamespace() and inAnyNamespace().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-cube/395)
=> Bump fabric8 kubernetes dependency version to 2.2.143

openshift/openshift/pom.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftRegistrar.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClient.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClientCreator.java, pom.xml
This pull requests makes the following changes:
- Align property names with cube-kubernetes (deprecates `originServer` in favor of `master.url`).
- Allows reading of properties from system and env ( system > env > arquillian.xml). 
- Parsing of definitions now is handled by the client instead of using jackson directly.
- Minor changes in the use of the client DSL.
=> Align arquillian-cube-openshift configuration with arquillian-cube-kubernetes

core/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java, core/src/main/java/org/arquillian/cube/impl/client/container/CubeContainerLifecycleController.java, core/src/main/java/org/arquillian/cube/impl/client/container/CubeRemoteCommandObserver.java, core/src/main/java/org/arquillian/cube/impl/client/container/ProtocolMetadataUpdater.java, core/src/main/java/org/arquillian/cube/impl/client/enricher/CubeIDResourceProvider.java, core/src/main/java/org/arquillian/cube/impl/util/ContainerUtil.java, core/src/test/java/org/arquillian/cube/impl/client/container/CubeContainerLifecycleControllerTest.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerAutoStartConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/container/DockerServerIPConfigurator.java
This is now supported by adding a "cubeId" property to the container config, e.g:
<property name="cubeId">alternativeId</property>
=> Allow custom mapping between container ID and cube ID (#451)

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/LogScanningAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Await.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/AwaitStrategyTest.java, docs/configuration.adoc
Fixes log await strategy issue #502 
- Change `LogScanningAwaitStrategy` to use an asynchronous way instead of polling. Basically when the container log contains the expected value, it unblocks the thread. With this approach we can add inspect log line by line instead as a batch, which causes some problems in some containers.
**Fixes**: #502
=> [issue #502] Log Strategy works with countdownlatch instead of polling.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/Ping.java, docker/docker/src/main/resources/org/arquillian/cube/docker/impl/await/wait-for-it-sh.sh, docker/docker/src/main/resources/org/arquillian/cube/docker/impl/await/wait-for-it.sh, docs/configuration.adoc, spi/src/main/java/org/arquillian/cube/spi/CubeOutput.java, spi/src/main/java/org/arquillian/cube/spi/metadata/CanExecuteProcessInContainer.java
This PR fixes #499 bug and improves how ping works by:
1. Copying Wait-For-It script from classpath location and not downloading from internet, so in cases of not having internet connection or for future customizations we don't relay on external site
2. Copy `wait-for-it` to `/tmp` to avoid any workspace problem inside docker containers.
3. Implementing fallback strategy so if _ss_ is not found in the container it automatically changes ping strategy to _wait-for-it_.
=> [issue #499] Copy waitforit script to /tmp and fallback strategy

docker/docker/src/main/java/org/arquillian/cube/docker/impl/requirement/DockerRequirement.java
It resolves serverUri depending on OS.
Currently all tests under ftest-docker-compose are ignoring due UnsatisfiedRequirementException.
- Correct mapping of resolver hash.
**Fixes**: #509
=> [Issue #509] Should fixes serverUri to check isDockerRunning.

docker/ftest/pom.xml, docker/ftest/src/test/java/org/arquillian/cube/servlet/CubeControllerTest.java, docker/ftest/src/test/java/org/arquillian/cube/servlet/HelloWorldServletTest.java, docker/ftest/src/test/resources/arquillian.xml, docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/ContainerStatsBuilder.java, docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/CubeStatistics.java, docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironment.java, docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java
Putting reporting parameters like IO, network, disk usage into a table form.
e.g.
| rx_bytes  |
| before | After | use |
| 10 | 12 | 2 |
-  Reporting statistics only after method with format shown above.
- Some cleanup of remoteAPI, serverURI from ftest module.
**Fixes**: #506
=> [Issue #506] Put reporting parameters like IO, network, disk usage into a table form

core/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java, core/src/test/java/org/arquillian/cube/impl/util/TestPortBindings.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/PortForwarder.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/ServiceCube.java, spi/src/main/java/org/arquillian/cube/spi/metadata/HasPortBindings.java
**Fixes**: #508
Make possible to configure the port forwarder server bind address.
In that way you can run more than once instance of the port forwarder
on the same machine.
=> [Issue-#508] - Make possible to configure the port forwarder server bind address

docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironment.java, docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java, pom.xml
Update the file path to relative path to avoid duplication in the file path entry while rendering the file location as link in the report.
- Relativize log file path for use by Recorder for generating reports. 
- Grouping file entry for better readability in generated reports.  
**Fixes**: #512
=> Updates file path to relative path and add file entry to group entry for improved readability in reports.

core/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java
If the user specifies the managementPort the if condition on line 71 will not be satisfied 
and the mappingForPort object will not be populated, so when the management address is getting
overridden it will throw an NPE exception when trying to do mappingForPort.getIP().
=> [Issue #517] - NPE at ContainerConfigurationController.remapContainer()

docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/utils/NumberConversion.java, docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/utils/NumberConversionTest.java
If there is negative number in container statistics then it should show proper human readable number with sign.
- Changed logic to show human readable format.
**Fixes**: #515
=> [Issue #515] Modifies logic to show negative numbers  in human readable format.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/StatsLogsResultCallback.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
Only tomcat container is stopping other thread execution even if call `onComplete()` event in StatsLogsResultCallback when you have added recorder dependency in your class path.
- Added CountDownLatch for StatsLogsResultCallback So even if after onComplete event is stopping execution of other thread, it'll timeout after timeout period.
**Fixes**: #519
=> Added CountLatch to use it for StatsCmd.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
In case of not setting a tag, all tags are downloaded
- if no tag is specified, latest is set by default.
**Fixes**: #523
=> In case that user does not specify a tag, latest is used by default.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolver.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolverTest.java
If docker host scheme is set to TCP, then TLS_VERIFY is set to true when it shouldn't.
- Add TCP scheme in logic in charge of deciding if TLS should be used or not.
**Fixes**: #525
=> Adds tcp scheme on tls_verify resolution

docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java
CubeConfiguratorTest is broken by 47dbf9d3f74c43c79100b018355b43e06216ae47.
Now that we add `tlsVerify` when `tcp` scheme is, the `certPath` will get removed. So we need to align tests accordingly.
=> Fix broken tests.

docker/ftest-restassured/src/test/java/org/arquillian/cube/restassured/PingPongTest.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RequestSpecBuilderResourceProvider.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredConfiguration.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredCustomizer.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RestAssuredExtension.java, docker/restassured/src/test/java/org/arquillian/cube/docker/restassured/RestAssuredCustomizerTest.java, docs/restassured.adoc
Instead of configuring RestAssured using static code, now users can inject `RequestSpecBuilder` in test with docker values initialized.
- RestAssured static code is not called anymore
- `RequestSpecBuilder` is injected with docker values
-
**Fixes**: #530
=> changes configuring restassuerd from static code to RequestSpecBuilder

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/locator/DefaultKubernetesResouceLocator.java
The fabric8-maven-plugin in version 3.x generates and stores kubernetes/openshift resources in a different directory.
It would be awesome if we also looked there, when we are trying to discover kubernetes/openshift resources.
=> Add support for the f-m-p version 3.x.

circle.yml
We need to run our tests on a machine that has at least docker available, so that @RequiresDocker is satisfied.
=> CircleCI now uses a machine with docker.

kubernetes/reporter/pom.xml, kubernetes/reporter/src/main/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformation.java, kubernetes/reporter/src/test/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformationTest.java, kubernetes/reporter/src/test/resources/kubernetes1.json, kubernetes/reporter/src/test/resources/replication_controller.json, kubernetes/reporter/src/test/resources/services.json, pom.xml
If user is running services using multiple configuration file, then all files should be display in reports
- Support for multiple files from local resources & from http url
**Fixes**: #539
=> Adds support for multiple config files in kubernetes reporter

docker/drone/src/main/java/org/arquillian/cube/docker/graphene/location/DockerCubeCustomizableURLResourceProvider.java, docker/drone/src/test/java/org/arquillian/cube/docker/graphene/location/CubeDockerCustomizableURLResourceProviderTest.java, docker/ftest-drone-custom/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docker/ftest-drone-reporter/src/test/java/org/arquillian/cube/drone/TodoBrowserTest.java, docker/ftest-graphene/src/test/resources/arquillian.xml, docs/drone.adoc, pom.xml
Grpahene `url` property should be a full URL with scheme.
- URL is the only attribute used in Cube and should be a full URL. This doesn't break anything since Graphene forces this.
**Fixes**: #551
=> update ftest to use internal container IP and fix Graphene bug

api/src/main/java/org/arquillian/cube/DockerUrl.java, core/src/main/java/org/arquillian/cube/impl/client/CubeExtension.java, core/src/main/java/org/arquillian/cube/impl/client/enricher/StandaloneCubeUrlResourceProvider.java, docker/ftest-standalone-autostart/src/test/java/org/arquillian/cube/StandaloneTestCase.java, docker/ftest-standalone-autostart/src/test/resources/arquillian.xml, docker/ftest-standalone/src/test/java/org/arquillian/cube/StandaloneTestCase.java, docs/enrichers.adoc
Currently when running Arquillian Cube in standalone mode, you have no way to inject a URL of kind `dockerhost:portbinding/context`, you need to construct yourself by enriching test with required data and then construct the URL.
```java
@DockerUrl(protocol="http", containerName = "helloworld", exposedPort = "8080", context = "/hello")
@ArquillianResource
URL url;
// Then URL would be the docker host IP + binding port of exposed port 8080 of container helloworld + context
```
```java
@HostIP
String ip;
@HostPort(containerName = "tomcat", value = 8080)
int tomcatPort;
@Test
public void test() {
new URL("http", ip, tomcatPort, "hello");
}
```
**Fixes**: #553
=> adds @DockerUrl annotation enrichment in URLs

api/src/main/java/org/arquillian/cube/containerobject/Environment.java, api/src/main/java/org/arquillian/cube/containerobject/Environments.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricherTest.java
Adds `@Environment` annotation support for Container objects
- Creates an environment annotation to set environment variables on running container
-
-
**Fixes**: #555
=> adds environment variable support in container objects

docker/ftest-restassured/src/test/java/org/arquillian/cube/restassured/PingPongTest.java, docker/restassured/src/main/java/org/arquillian/cube/docker/restassured/RequestSpecBuilderResourceProvider.java
Adds support for @DockerUrl annotation in RestAssured integration
- Overrides RequestSpecBuilder with `@DockerUrl` annotation
-
-
**Fixes**: #565
=> Adds support for @DockerUrl annotation in RestAssured integration

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/NamespaceService.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionCreatedListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java
We only use NamespaceService.clean() method only before we destroy a namespace, which is so redundant.
Let's stop using it and deprecate it, before we completely wipe it.
=> Deprecate and stop using redundant method.

api/src/main/java/org/arquillian/cube/ContainerObjectConfiguration.java, api/src/main/java/org/arquillian/cube/ContainerObjectFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/ContainerObjectFactoryRegistrar.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerExtension.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/ContainerObjectFactoryProvider.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricher.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/ContainerObjectUtil.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricherTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilderTest.java, docker/docker/src/test/resources/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilderTest/TestContainerObjectDefinedUsingDockerfile/Dockerfile, docs/cop.adoc
Allows creating cubes from container objects programmatically
- A new interface injectable inside Arquillian test classes: ```ContainerObjectFactory```
- support for programmatically creating container objects with ```factory.createContainerObject(...)```. Created container objects will work exactly as if they were created by injecting them as fields. Associated Cube instances can also be stopped/destroyed using an injected ```CubeController```
**Fixes**: #564
=> Allows creating cubes from container objects programmatically

kubernetes/fabric8/src/main/java/org/arquillian/cube/kubernetes/fabric8/impl/annotation/Fabric8AnnotationProvider.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/NamespaceService.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SuiteListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/TestListener.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java
This pull request adds the following:
- when in openshift annotate project and not namespace
- make sure annotations are already there when creating ns/project(can't just add annotations).
- catch and log exception occuring during ns/project annotation.
=> Fix for 585

docker/ftest-boot2docker/src/test/resources/tomcat/Dockerfile, docker/ftest-docker-compose-v2-git-context/docker-compose.yml, docker/ftest-docker-compose-v2/src/test/resources/tomcat/Dockerfile, docker/ftest-docker-compose/src/test/resources/tomcat/Dockerfile, docker/ftest/pom.xml, docker/ftest/src/test/java/org/arquillian/cube/servlet/CubeControllerTest.java, docker/ftest/src/test/resources/arquillian.xml, docker/ftest/src/test/resources/tomcat/Dockerfile
Functional tests are failing when we try to run it  tutum/tomcat:7.0 from docker/ftest.
It is skipping on travis as it needs docker-machine to run. So we couldn't analyse this before.
- Removed all unnecessary tomcat configuration.
- Adds tomcat:jre8 image
@lordofthejars Can you please check docker-machine ftests to execute on your machine?
=> Changed tomcat 7 image to use jre8.

core/src/main/java/org/arquillian/cube/impl/model/CubeId.java, core/src/main/java/org/arquillian/cube/impl/model/CubeIdFactory.java, core/src/main/java/org/arquillian/cube/impl/model/DefaultCubeId.java, core/src/main/java/org/arquillian/cube/impl/model/LocalCubeRegistry.java, core/src/main/java/org/arquillian/cube/impl/model/ParallelizedCubeId.java, core/src/main/java/org/arquillian/cube/impl/model/StarredCubeId.java, core/src/test/java/org/arquillian/cube/impl/model/CubeIdFactoryTest.java, core/src/test/java/org/arquillian/cube/impl/model/LocalCubeRegistryTest.java, docker/ftest-standalone-star-operator/pom.xml, docker/ftest-standalone-star-operator/src/test/java/org/arquillian/cube/StandaloneStarOperatorTestCase.java, docker/ftest-standalone-star-operator/src/test/resources/arquillian.xml, docker/pom.xml, docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java, docs/parallel.adoc
As reported in [ISSUE 392](https://github.com/arquillian/arquillian-cube/issues/392), it is not possible to use `@HostPort` and `@DockerUrl` when using the star operator.
**Fixes**: #392
=> [ISSUE #392] Fixed: Using star operator with @HostPort and @DockerUrl

bom/pom.xml
We have added bom support. Looks like I missed type in dependencyManagement sections dependency type pom due to which couldn't import from bom.
- Adds missing type bom.
=> fixed missing type - pom

.travis.yml
Maven wrapper is part of the source code so no installation is required.
- Remove before_install step in .travis.yml
**Fixes**: #
=> Remove travis's before_install step

docker/ftest-docker-compose-v2-git-context/pom.xml, docker/ftest-drone-custom/pom.xml, docker/ftest-drone-reporter/pom.xml, docker/ftest-drone/pom.xml, docker/ftest-graphene/pom.xml, docker/ftest-restassured/pom.xml
Existing modules inherit assertj's version 3.6.1 but some modules
override this version. This commit polish pom files which override
version declared in dependencyManagement section.
- Remove tag `version` where `assertj.version` is overriden
**Fixes**: #
=> Polish pom for assertj

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/DockerCompositions.java, docker/ftest-standalone-star-operator-docker-compose/src/test/resources/arquillian.xml
If user uses `customSettings` in `docker-compose` format and the cube id is not found then an exception is thrown because `String.format` contains an invalid syntax.
-
-
-
**Fixes**: #620
=> Fixes String format syntax

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectFactory.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilderTest.java, docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/PingPongTest.java
Checks if container object is already up before initializing it. If more than one test uses the same container object, the test fails because the container is already initialized.
-
-
-
**Fixes**: #610
=> Checks if container object is already up before initializing it

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/ResourceInstaller.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManagerLifecycle.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/install/DefaultResourceInstaller.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, pom.xml
Originally, there was the concept of `namespace cleanup` and `namespace destroy`. During the move to `arquillian-cube` both concepts collapsed into `namespace destroy`.
However, there is a valid use case "Use a single namespace/project, don't delete but clean it up". In fact in restricted environment this is likely to be the most common use case, so we need to be able to handle it.
This pull request, fixes cleanup vs destroy so that we can selectively do both.
=> Ns cleanup destroy

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java
Add support for port range definition in docker-compose format
**Fixes**: #647
=> Add support for port range definition

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java
Hi, 
thanks for adding the volume mount fix so quickly. This small change covers also a possible specification of the mount permission (i.e. /source:/target:ro) and ensures that in that case also the volume is taken from element 1 of the split result.
Best regards.
=> Added condition to cover also a possible specification of the mount permission (i.e. /source:/target:ro)

docker/docker/src/main/java/org/arquillian/cube/docker/impl/requirement/DockerMachineRequirement.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/requirement/DockerRequirement.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/requirement/DockerMachineRequirementTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/requirement/DockerRequirementTest.java
Catching `org.arquillian.spacelift.execution.ExecutionException` in `DockerRequirement` so that a test can be skipped if none of the Docker, Docker Machine or Boot2Docker executables can be found on the host. 
Currently the uncaught exception causes any `@RequiresDocker` annotated tests to fail.
=> Fixes #660. Gracefully handle ExecutionException in DockerRequirement

api/src/main/java/org/arquillian/cube/Sleep.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/SleepBeforeClassObserver.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerExtension.java, docs/configuration.adoc
Adds `@sleep` annotation to pause a test the specified timespan before executing all the test methods.
-
-
-
**Fixes**: #681
=> Adds sleep annotation

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/HttpAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/AwaitBuilder.java
Adds shortcuts for http and https await
- Added `httpAwait` and `httpsAwait` on `AwaitBuilder`
**Fixes**: #683
=> Adds shortcuts for http and https await

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/Container.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/RedisTest.java, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/ContainerDslRule.java
Adds `getLog` and `exec` methods in container object dsl.
**Fixes**: #685
=> Adds extra operations to execute command and get log from container

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
This pull request addresses two issues:
- adds the ability to use the current namespace (without requiring us to be explicit)
- fixes a minor glitch that prevented the Openshift resource locator to be properly registered.
both issues have been reported as part of: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/52
=> Use current namespace and fix Openshift resource locator

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java
Now setting environment config url by looking under META-INF/fabric8/ directory.
- Cube is looking under META-INF/fabric8 directory as well while findingResource.
**Fixes**: #705
=> Now finding resources from META-INF/fabric8 using env.config.resource.name 

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/ConfigUtil.java, docker/ftest-standalone-star-operator/src/test/java/org/arquillian/cube/StandaloneStarOperatorTestCase.java, docker/ftest-standalone-star-operator/src/test/resources/arquillian.xml, docker/ftest-standalone-star-operator/src/test/resources/containers.yml
fix(#730): Adds Docker Compose variable substitution to cube format
=> fix(#730): Adds Docker Compose variable substitution to cube format

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
We should keep the default value as "true" regardless of whether we
are going to destroy the namespace or not. This is to keep consistency
when users call "configuration.isNamespaceCleanupEnabled()".
Users of this library can rely on the above method to decide when
to cleanup stuff they have created. So, the library must be
consistent on their flags and documentation.
Closes #747.
=> Kubernetes/Openshift: Defaults "namespace.cleanup.enabled" to true

docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/SeleniumContainersTest.java
Docker drone is expecting the wrong responseCode for Selenium from version 3 onwards
- Retrieve Selenium major version from image tag
- For version >= 3 and as default (e.g. to cover "latest" tag) expect 200 response code
- For versions < 3 expect 403 response code
**Fixes**: #736
=> Fix for #736: Expect response code 200 for Selenium containers version >= 3

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java
Add a FIXME comment about this behavior. Once Openshift supports it, this
can be reverted.
Closes #740.
=> Openshift: Make annotate() a NOOP since it's not supported on Openshift

docker/drone/src/main/java/org/arquillian/cube/docker/drone/VncRecorderLifecycleManager.java
Fixes FileSystemException when using vnc recording under Windows
- Stop VNC recorder before moving recording file
**Fixes**: #761
=> Stop VNC recorder before moving recording file

docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java
Invalid bind for vnc / flv2mp4 containers running under Windows
-Convert host path to docker machine compatible bind for vnc / flv2mp4 containers when running under Windows
**Fixes**: #762
=> Convert recording path to Docker machine compatible bind when running on Windows

kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/PortForwarderTest.java
Move the PortFowarder tests from openshift package to kubernetes as the port forwarder was code was moved to the kubernetes.
=> Move the PortFowarder tests to kubernets module

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/portforward/PortForwardServerConnection.java
On every situation, so that it doesn't hang like the thread dump
below shows (PortForwardServerConnection.java:124 is the guilty
guy here):
```
"PortForwarding for cearq-amq63-2cec0671/testrunner task-4" #455 prio=5 os_prio=0 tid=0x00007f5a4433c000 nid=0x55ec waiting on condition [0x00007f59ea02b000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000006ca0e7ed0> (a java.util.concurrent.CountDownLatch$Sync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
at …
```
=> PortForwarder: Make sure to release the error channel latch

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftSuiteLifecycleController.java
It's the Configuration class that gets injected, not
CubeOpenShiftConfiguration, so, this second parameter will
never be resolved and thus the method will never be invoked.
This suppresses the following warning:
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.startAutoContainers is null. It won't be invoked.
=> Openshift: Fix @Observer parameter

core/src/main/java/org/arquillian/cube/impl/util/ConfigUtil.java, openshift/openshift/pom.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURL.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
This commit aggregate a useful functionality ported from CE-ARQ (https://github.com/jboss-openshift/ce-arq) that allows user to get the routes to their services just by using the @RouteURL annotation in the test class, example:
```
@RouteURL("eap-app")
private URL routeToMyApp
```
**Fixes**: #744
=> Move RouteURL functionality from ce-arq

core/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java
This fixes a potential null pointer exception when getting default container ports.
Observed running against a remote glassfish container. 
https://github.com/arquillian/arquillian-cube/issues/789
=> Fix potential NullPointerException

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/StarOperator.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDroneConfiguration.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/VideoConversionLifecycleManager.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/VncRecorderLifecycleManager.java, docker/drone/src/main/java/org/arquillian/cube/docker/graphene/location/DockerCubeCustomizableURLResourceProvider.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/SeleniumContainersTest.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/VncRecorderLifecycleManagerTest.java, docker/drone/src/test/java/org/arquillian/cube/docker/graphene/location/CubeDockerCustomizableURLResourceProviderTest.java, docs/drone.adoc
Enables running tests using Cube Drone in parallel.
- Two new cubedrone configuration options
- containerNameStrategy
- containerNamePrefix
- STATIC name strategy: same behaviour as before
- STATIC_PREFIX name strategy: Adds a configurable prefix to the static container name
- RANDOM name strategy: Adds a random UUID to the container name
STATIC_PREFIX and RANDOM also cause a random port being picked for the Selenium bound port.
**Fixes**: #791
=> Drone parallel test support

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ComposeBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/simple-docker-compose-network-aliases-v2.yml, docker/ftest-docker-machine-network/docker-compose.yml, docker/ftest-docker-machine-network/src/test/java/org/arquillian/cube/servlet/PingPongTest.java
Adds support for configuring network aliases similiar to ip4/6 address support (taken from first network of a service)
**Fixes**: #793
=> Add support for network aliases

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/DockerCompositions.java
Allow specifying alwaysPull through cubeSpecificProperties when using Compose format.
**Fixes**: #800
=> Set alwaysPull through cubeSpecificProperties

docker/drone/src/main/java/org/arquillian/cube/docker/drone/VideoConversionLifecycleManager.java
Prevents "java.lang.IllegalArgumentException: Video conversion cube is not present in the registry." being thrown when recording is disabled.
**Fixes**: #804
=> Don't start flv2mp4 container when recordingMode is NONE

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURL.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
With this change, `@RouteURL` injection works even if `routerHost` isn't configured.
- Remove the check for `routerHost` in `RouteURLEnricher`.
- Remove unreadable text in `@RouteURL` javadoc.
**Fixes**: #802
=> skip the routerHost check in RouteURLEnricher

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/KubernetesResourceLocator.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/locator/DefaultKubernetesResourceLocator.java, kubernetes/reporter/src/main/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformation.java, kubernetes/reporter/src/test/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformationTest.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/locator/OpenshiftKubernetesResourceLocator.java
This fixes #815.
Defaulted the imagestream detection to `true` when running on Openshift.
Deferred the choice of `kubernetes.json`/`openshift.json` file to a later stage (if not explicitly set by the user) when it's known if we are connected to a Kubernetes or Openshift cluster.
=> Fix Kubernetes-Openshift compatibility

docs/enrichers.adoc, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/AwaitRoute.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURL.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
The process that injects `@RouteURL`-s now awaits availability
of those routes. This can be configured using the `await`
parameter of the `@RouteURL` annotation.
I'm sending this PR just to start a discussion. I know Cube already awaits pod readiness, but this awaits the _route_. This is because there might be slight delay between pod becoming ready and being exposed on the router, and actually there's also a bug (I believe) on OpenShift Online where the delay between pod readiness and route availability can be several minutes!
=> add @AwaitRoute

pom.xml
Updates Docker Java client to latest version
- Updates Docker Java client to latest version 3.0.14
Fixes #829
=> fix(#829): Updates Docker Java client to latest version

docs/enrichers.adoc, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/AwaitRoute.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURL.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
This commit improves `@RouteURL` injection in these ways:
- The `@AwaitRoute` annotation is now external to `@RouteURL`, so
that the entire route await mechanism is opt-in. This isn't
a breaking change because the `@AwaitRoute` mechanism doesn't
exist in any release.
- The `@RouteURL` annotation now has a parameter to customize
the path portion of the injected URL.
- the `@RouteURL` injection now doesn't add a port number to the URL
if it's the default value for given protocol. This means the URLs
will be more inline with users expectations.
Fixes #837, fixes #838 and fixes #839.
=> improve route URL injection

docs/kubernetes.adoc
Fixes typos and formatting for the Kubernetes documentation.
- Fixes table formatting and nested indentation for lists and some phrasing and typos.
Fixes #858
=> chore: fixes typos and formatting in kubernetes.adoc

docs/kubernetes.adoc, kubernetes/kubernetes/pom.xml, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/utils/CommandExecutor.java, openshift/ftest-oc-proxy/pom.xml, openshift/ftest-oc-proxy/src/test/java/org/arquillian/cube/openshift/ftest/HelloWorldTest.java, openshift/ftest-oc-proxy/src/test/resources/arquillian.xml, openshift/ftest-oc-proxy/src/test/resources/openshift.json, openshift/pom.xml
Now you can execute any `oc` or `kubectl` command as a part of your tests.
-  Adds `CommandExecutor` class to execute any command using spacelift
Add kubernetes-client dependency on classpath
```xml
<dependency>
<groupId>org.arquillian.cube</groupId>
<artifactId>arquillian-cube-kubernetes</artifactId>
<version>${project.version}</version>
<scope>test</scope>
</dependency> 
```
Write a test like following
```java
@Test
public void should_be_able_deploy_resources_using_oc() {
// given
final CommandExecutor commandExecutor = new CommandExecutor();
// when
final List<String> resources = commandExecutor.execCommand("oc create -f https://goo.gl/qaiGRJ");
// then
assertThat(resources).contains("service \"hello-world\" created", "deployment \"hello-world\" created");
}
```
Fixes #830
=> feat(#830): support oc or kubectl command to execute as a part of your tests.

openshift/ftest-openshift-resources-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftResourcesTest.java, openshift/ftest-openshift-resources-standalone/src/test/resources/hello-route.yaml, openshift/openshift/pom.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/fabric8/F8OpenShiftAdapter.java
@OpenShiftResource supports `yaml` format
- Adds snakeyaml to process yaml format in case of cannot be parsed as json
Fixes #850
=> fix(#850): @OpenShiftResource supports yaml format

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CEEnvironmentProcessor.java
This piece of code was added when we did't have the ability to copy the
logs from pods. Now we have it, so, it's up to the user enable in order
to debug issues.
See https://github.com/jboss-openshift/ce-arq/commit/e68f78ae54b7a0fad4b81a0040faa1eebf61a0b6
=> Do not log events upon failure, we have "logs.copy" property for that

docs/kubernetes.adoc
They were dropped by commit 63a74049d123
=> Bring 'logs.(copy|path)' docs back to life

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
As a part of https://github.com/arquillian/arquillian-cube/pull/868/files, we are setting waitEnabled to true only for DefaultKubernetes configuration which is working fine for k8s extension. Check code [here](https://github.com/arquillian/arquillian-cube/pull/868/files#diff-6532ea423d1c6b77a83466b11a4b6240R150)
We should set it to `CubeOpenShiftConfiguration`
Fixes #876
=> fix(#876): Set wait enables to true for openshift env to be ready

kubernetes/ftest-kubernetes-reporter/src/test/resources/kubernetes.json, kubernetes/ftest-kubernetes/src/test/java/HelloWorldTest.java, kubernetes/ftest-kubernetes/src/test/resources/kubernetes.json, openshift/ftest-standalone/pom.xml, openshift/ftest-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldTest.java
- Changed `dockercloud/hello-world` to `openshift/hello-openshift:v3.6.0`
- Uses k8-client version in ftest as per documentation
Fixes #880
=> Docker image compatible with minishift to work all ftest from cube-k8s

openshift/api/src/main/java/org/arquillian/cube/openshift/api/OpenShiftResource.java, openshift/api/src/main/java/org/arquillian/cube/openshift/api/OpenShiftResources.java, openshift/ftest-openshift-resources-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftResourcesTest.java, openshift/ftest-openshift-resources-standalone/src/test/resources/hello-route-2.yaml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CEEnvironmentProcessor.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/resources/OpenShiftResourceFactory.java
You can set OpenShift resources using `@OpenShiftResources` annotation at method level, so resources are created before the test and deleted after the test.
- `@OpenShiftResources` at method level
- Observers for creating resources before and after each test method execution.
Fixes #860
=> feat(#860): Set OpenShift resources at method level

.travis.yml, openshift/ftest/src/test/java/org/arquillian/cube/openshift/ftest/HelloPodDeploymentOpenShiftTestCase.java
Running `oc cluster up` on travis.
- Starting cluster using `oc cluster up` to start openshift cluster.
- Using matrix to run tests on different cluster
Fixes #882
=> Cube CI is using oc cluster up to run all ftests from k8s & openshift

.travis.yml
As `nip.io` is down let's try to run the tests using `xip.io` instead.
=> fix: routing using xip.io

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/install/DefaultResourceInstaller.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/install/OpenshiftResourceInstaller.java
The resource installer for Openshift is currently unusable, as it doesn't override the `toImmutable()` method which returns an immutable instance of its super class.
This pull request fixes that and also adds some more logging.
=> fix: Openshift resource installer.

pom.xml
Upgrades to Kubernetes Client version 3.1.5 from 3.1.0 due to a potential bug, [fabric8io/kubernetes-client#918](https://github.com/fabric8io/kubernetes-client/issues/918) in the older version
Fixes #899
=> chore #899: updates kubernetes client version to 3.1.5 from 3.1.0.

openshift/ftest-openshift-graphene/src/test/java/org/arquillian/cube/openshift/ftest/TodoBrowserTest.java
As this test assumes OpenShift to be available we should require it explicitly
=> fix(test): requires openshift for graphene integration

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistant.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/ResourceUtil.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/graphene/location/OpenshiftCustomizableURLResourceProvider.java
Adds `Await Route` validation check to ensure readiness of the route before execution of the Graphene Integration Tests which might otherwise fail due to not ready state of the route. 
- Abstracts Await Route Logic to ResourceUtil class. 
- Refactors awaitRoute for RouteUrlEnrichers and OpenshiftAssistant classes.
- Adds await route for openshift graphene integration.
Fixes #911
=> Adds check for route readiness for openshift-graphene integration.

kubernetes/ftest-kubernetes-logs/src/test/resources/kubernetes.json, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java
Fixes intermittent failing ftest-kubernetes-logs
- Adds readynessprode for pod container
Fixes #919
=> fix(#919): Adds readyness probe for k8s logs ftest

docs/kubernetes.adoc
Updates documentation to include static links to Arquillian Kube Recipes.
Fixes #834
=> chore(docs): adds static links to kube-repices in docs.

docs/kubernetes.adoc, openshift/ftest-openshift-graphene/src/test/java/org/arquillian/cube/openshift/ftest/TodoBrowserTest.java, openshift/ftest-openshift-restassured/pom.xml, openshift/ftest-openshift-restassured/src/test/java/org/arquillian/openshift/restassured/HelloOpenShiftRestAssuredTest.java, openshift/ftest-openshift-restassured/src/test/java/org/arquillian/openshift/restassured/PingPongTest.java, openshift/ftest-openshift-restassured/src/test/resources/arquillian.xml, openshift/ftest-openshift-restassured/src/test/resources/openshift.json, openshift/openshift-restassured/pom.xml, openshift/openshift-restassured/src/main/java/org/arquillian/cube/openshift/restassured/AuthenticationSchemeFactory.java, openshift/openshift-restassured/src/main/java/org/arquillian/cube/openshift/restassured/RequestSpecBuilderResourceProvider.java, openshift/openshift-restassured/src/main/java/org/arquillian/cube/openshift/restassured/RestAssuredConfiguration.java, openshift/openshift-restassured/src/main/java/org/arquillian/cube/openshift/restassured/RestAssuredConfigurator.java, openshift/openshift-restassured/src/main/java/org/arquillian/cube/openshift/restassured/RestAssuredCustomizer.java, openshift/openshift-restassured/src/main/java/org/arquillian/cube/openshift/restassured/RestAssuredExtension.java, openshift/openshift-restassured/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, openshift/openshift-restassured/src/test/java/org/arquillian/cube/openshift/restassured/AuthenticateSchemeFactoryTest.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftRouteLocator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/graphene/location/OpenShiftCustomizableURLResourceProvider.java, openshift/pom.xml, pom.xml
Creates Rest-Assured Integration with OpenShift to auto-resolve the base URI for the application deployed on OpenShift.
- Implements OpenShift RestAssured extension.
- Adds sample ftest for the same.
- Abstracts common openshift route logic. 
Fixes #894
=>  feat#894: Creates RestAssured integration with OpenShift routes.

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
Add a hint about the available routes when you specify a invalid route name, like the example below:
```
@RouteURL("kie-app")
private URL routeURL;
```
With this change a message similar to this will be printed within the stacktrace:
> Caused by: java.lang.IllegalArgumentException: Could not resolve route: kie-app. Available routes: [kie-app-kieserver, secure-kie-app-kieserver]
It could be helpful when you are unsure about the route name, and instead to configure the arquillian to do not remove the test project to check the route names,
it is easier to have it on the stacktrace.
=> Improve could not resolve route message

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesAssistant.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/enricher/external/KubernetesAssistantResourceProvider.java, openshift/ftest-openshift-assistant/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftAssistantTest.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistant.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftRouteLocator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/external/OpenShiftAssistantResourceProvider.java
Abstract the common logic from the Kubernetes and OpenShift Assistants to Kubernetes Assistant and extend the same to OpenShift Assistant.
- Removes duplicate code logic from OpenShift Assistant.
- Fixes `canProvide` method for provider classes.
Fixes #924
=> chore(#924): Abstract common logic to Kubernetes Assistant and extend it to OpenShift Assistant

docs/kubernetes.adoc, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/reporter/src/test/java/org/arquillian/cube/kubernetes/reporter/TakeKubernetesResourcesInformationTest.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
https://github.com/arquillian/arquillian-cube/issues/931
- use a comma (and arbitrarily long string of whitespace chars) instead of just whitespaces to separate multiple values specified in `arquillian.xml` configuration file
=> ENVIRONMENT_DEPENDENCIES are now separated by comma

docs/kubernetes.adoc
Applies a small fix to the wording of the sections that describes how the namespace is resolved
=> Make minor documentation fix

core/src/main/java/org/arquillian/cube/impl/client/ForceStopDockerContainersShutdownHook.java
- We are not checking state in shutdown hook as it's already checked in `stop` and `destroy` 
Fixes #939
=> fix(#939): improves shutdown hook to stop and remove container

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/StarOperator.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, docs/parallel.adoc
If you're using networks and you want to parallelize your containers,
all the containers will end up on the same set of networks, which
could interfere with your test.
Even worse, as docker allows multiple networks with the same name, if
there's a problem with cleanup on a previous run, you may end up with
containers in different networks when you want them to be in the same
network.
This patch solves these problems by allowing the star pattern for
networks. It works the same as the container star pattern, and
networkMode and networks are updated within the container configuration.
=> Allow parallelization of networks

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, docker/docker/src/test/resources/test-topologies/topology1.yaml, docs/configuration.adoc
Allow users to specify the docker configuration file as a file on the
classpath, rather that on the filesystem. This means they won't have
to worry about absolute and relative paths, which can change in maven
depending on which flags are specified (forkCount for example).
It also allows configurations to be bundled into a jar and shared
between modules.
=> Allow docker configuration to be loaded from the classpath

kubernetes/ftest-kubernetes-assistant/pom.xml, openshift/ftest-oc-proxy/pom.xml, openshift/ftest-openshift-assistant/pom.xml, openshift/ftest-openshift-resources-standalone/pom.xml, openshift/ftest-openshift-restassured/pom.xml, openshift/ftest-standalone/pom.xml, openshift/ftest-template-standalone/pom.xml, requirement-spi/pom.xml
Should skip releasing ftests jars to maven central.
- Set `maven-deploy-plugin` in pom.xml for ftest modules.
Fixes #951
=> fix(#951): sets plugin to skip publishing ftest artifacts to maven central.

core/src/main/java/org/arquillian/cube/impl/client/ForceStopDockerContainersShutdownHook.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/metadata/ReportMetrics.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/model/DockerCubeTest.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, spi/src/main/java/org/arquillian/cube/spi/Cube.java
- Changed default state from `DESTROYED` to `BEFORE_CREATE`
- Now checking state while stopping container
Fixes #957
=> fix(#957): improves cube not to stop container if it's already destroyed

openshift/ftest-openshift-assistant-template/pom.xml, openshift/ftest-openshift-assistant-template/src/test/java/org/arquillian/cube/openshift/standalone/HelloOpenShiftAssistantTemplateTest.java, openshift/ftest-openshift-assistant-template/src/test/resources/hello-template.yaml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistant.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistantTemplate.java, openshift/pom.xml
Creates Template DSL for OpenShiftAssistant so you can apply templates programmatically.
This DSL looks like:
`openshiftAssistant.usingTemplate("url/to/template").parameter("param1", "value1").parameter("param2", "value2").deploy()`
- Template DSL for OpenShift Assistant.
- ftest to showcase template DSL for OpenShift Assistant.
Fixes #934
=> feat(#934): introduces template dsl for openshift assistant.

openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/adapter/OpenShiftAdapterFactory.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/adapter/OpenShiftAdapterProvider.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/GitServer.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClient.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClientCreator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/fabric8/F8OpenShiftAdapter.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/fabric8/F8OpenShiftAdapterProvider.java
Reuse the same OpenShiftClient instead of instantiating a new one
- Uses the OpenShiftClient instance that are injected into Arquillian scope
Fixes #986
=> fix(#986): Reuse the same OpenShiftClient instead of instantiating a new one

bom/pom.xml, openshift/ftest-istio-openshift/pom.xml, openshift/ftest-oc-proxy/pom.xml, openshift/ftest-openshift-assistant-template/pom.xml
- Adds arquillian-cube-*-starter to arquillian-cube-bom
- Changed ftests to use starter dependency 
- corrected dependency in openshift/ftest-oc-proxy/pom.xml
Fixes #992
=> fix(#992): adds all starter dependency in cube-bom

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfigurationFactory.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfigurationFactory.java
Enabling printing Kubernetes and OpenShift configuration parameters in Console.
- defines toString() methods for Kubernetes and OpenShift Configuration classes.
- makes calls to Kubernetes and OpenShift Configuration classes' toString() methods from respective configuration factory classes.
Fixes #981
=> chore(#981): enables printing k8s/openshift configuration parameters to console.

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java
Logs warning to run fabric8-maven-plugin first, if FMP used and no Kubernetes resource found.
- Updates logger message.
Fixes #977
=> chore(#977): updates logger message to include FMP warning.

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/api/Configuration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfiguration.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfiguration.java
If the current namespace is set, then querying `client.getNameSpace()` causes user developer authentication issue.
```
io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException: Failure executing: GET at: https://api.starter-us-east-2.openshift.com/api/v1/namespaces/myproject. Message: Forbidden! User developer/192-168-42-73:8443 doesn't have permission. User "dipakpawar231" cannot get namespaces in the namespace "myproject": User "dipakpawar231" cannot get namespaces in project "myproject".
```
- skip checking existence of namespace if property `namespace.use.current` is set.
Fixes #983
=> fix(#983): skip checking existence of namespace if namespace.use.current set.

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolver.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerMachineDistro.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/requirement/DockerRequirement.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/DefaultDocker.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystem.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystemFamily.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystemFamilyInterface.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystemInterface.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystemResolver.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolverTest.java, docker/docker/src/test/resources/docker.sock, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/DockerClientInitializer.java, docker/reporter/src/test/java/org/arquillian/cube/docker/impl/client/utils/NumberConversionTest.java
As discussed in #883, here is an implementation to consider the default docker configuration before running `docker-machine` or `boot2docker`
Fixes #883
=> Add support for default docker configuration

core/pom.xml, core/src/main/java/org/arquillian/cube/impl/ConfigurationParameters.java, core/src/main/java/org/arquillian/cube/impl/EnricherExpressionResolver.java, core/src/test/java/org/arquillian/cube/impl/EnricherExpressionResolverTest.java, docs/enrichers.adoc, openshift/ftest-openshift-resources-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftResourcesIT.java, openshift/ftest-openshift-resources-standalone/src/test/resources/arquillian.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfigurationFactory.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/RouteURLEnricher.java
- Introducing `ConfigurationParameters` class to store configuration read from arquillian.xml
- Creating ApplicationScoped Instance of `ConfigurationParameters` to store config params.
- Using store ConfigParams while resolving Enricher expression. 
Fixes #996
=> feat(#996): inject arquillian.xml properties in @RouteUrl

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/AwaitStrategyFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/DockerHealthAwaitStrategy.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Await.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/AwaitStrategyTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/DockerHealthAwaitStrategyTest.java, docker/docker/src/test/resources/DockerHealthAwait/HealthFailure/Dockerfile, docker/docker/src/test/resources/DockerHealthAwait/HealthSuccess/Dockerfile, docs/configuration.adoc
Add support for docker based health checks
This commit adds support for docker-managed health checks.
There are 2 ways of using it:
- either let docker manage the health check on its own and inspect the
status thanks to the docker API
- or use the docker API to run a custom health check command in the
container
=> Docker health

openshift/openshift/pom.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/model/BuildablePodCube.java, openshift/openshift/src/test/java/org/arquillian/cube/openshift/impl/DnsServiceTest.java, openshift/openshift/src/test/java/org/arquillian/cube/openshift/impl/model/BuildablePodCubeTest.java
Adds state checks before `stop` and `destroy` events for BuildablePodCube to fix NPE.
- Adds state checks before `stop` and `destroy` events for BuildablePodCube
- Adds Unit Tests for the Lifecycle Events. 
Fixes: #1006
=> fix(#1006): adds state checks in BuildablePodCube stop and destroy lifecycle events.

kubernetes/kubernetes/pom.xml, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/ClientConfigBuilder.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/ClientConfigurator.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/ClientCreator.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/DefaultConfigurationFactory.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/ExtensionRegistrar.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/requirement/KubernetesRequirement.java, openshift/ftest-standalone/src/test/resources/arquillian.xml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/CubeOpenshiftExtension.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/CubeOpenShiftConfigurationFactory.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftRequirement.java, pom.xml
1. Reads extension configuration to initialize K8Client with Remote Cluster in Kubernetes/Openshift Requirement.
2. Fixes IllegalArgumentException due to the addition of multiple org.jboss.shrinkwrap.api.Archive deployments with the same name: DEFAULT.
- reads extension configuration from `Arquillian Descriptor` exposed from [Arquillian Core](https://github.com/arquillian/arquillian-core/pull/165) in Kubernetes and OpenShift Requirement. 
- extracts ConfigBuilder logic to ClientConfigurator class.
- Updates Arquillian Core Version.
- Overrides AnnotationDeploymentScenarioGenerator service with the registered ExternalDeploymentScenarioGenerator service.
Fixes  https://github.com/arquillian/arquillian-core/issues/166,  #984
=> fix(#984): reads configuration to initialize K8Client in Kubernetes/Openshift Requirement.

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesAssistant.java, openshift/ftest-openshift-assistant/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftAssistantIT.java, openshift/ftest-openshift-assistant/src/test/resources/deployment.yml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistant.java
If user is deploying pod with deploymentconfig, it creates extra pod which ends with `-deploy` to manage replica. We should filter it for `awaitApplicationReadinessOrFail`
-  filter pods ends with `-deploy`
- Adds ftest
Fixes #1011
=> fix(#1011): filter pods ends with -deploy in awaitApplicationReadine

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/WatchListener.java
Increases verbosity by appending watcher logs for events to console if resources are not in the ready state. 
```
LASTSEEN             FIRSTSEEN          COUNT  NAME                       KIND  SUBOBJECT       TYPE     REASON     SOURCE                   MESSAGE
2018-03-05T05:14:20Z 2018-03-05T05:14:20Z 1 hello-openshift.1518ee466716f9c9 Pod null Normal Scheduled EventSource(component=default-scheduler, host=null, additionalProperties={}) Successfully assigned hello-openshift to localhost
2018-03-05T05:14:21Z 2018-03-05T05:14:21Z 1 hello-openshift.1518ee4692267810 Pod spec.containers{hello-openshift} Normal Pulled EventSource(component=kubelet, host=localhost, additionalProperties={}) Container image "openshift/hello-openshift" already present on machine
2018-03-05T05:14:21Z …
```
=> fix(#1001): logs watcher events to console if resources not in the ready state.

kubernetes/ftest-kubernetes-assistant/src/test/resources/kubernetes.json, kubernetes/ftest-kubernetes-logs/src/test/resources/kubernetes.json, kubernetes/ftest-kubernetes-reporter/src/test/resources/kubernetes.json, kubernetes/ftest-kubernetes-resources/src/test/resources/hello-world-2.yaml, kubernetes/ftest-kubernetes-resources/src/test/resources/hello-world.yaml, kubernetes/ftest-kubernetes/src/test/resources/kubernetes.yaml, openshift/ftest-containerless/src/test/resources/hello_pod.json, openshift/ftest-oc-proxy/src/test/resources/openshift.json, openshift/ftest-openshift-assistant/src/test/resources/openshift.json, openshift/ftest-openshift-graphene/src/test/resources/openshift.json, openshift/ftest-openshift-resources-standalone/src/test/resources/hello-openshift.json, openshift/ftest-openshift-restassured/src/test/resources/openshift.json, openshift/ftest/src/test/resources/hello_pod.json
K8s/openshift has default imagePullPolicy to always, which will try to pull image even if it's present on hosts which needs some time. Updated `imagePullPolicy: ifNotPresent` to reduce build time
Fixes #1026
=> fix(#1026): update imagePullPolicy to IfNotPresent

kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesAssistant.java, openshift/ftest-openshift-assistant/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldOpenShiftAssistantIT.java, openshift/ftest-openshift-assistant/src/test/resources/deployment.yml, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftAssistant.java
The method **awaitApplicationReadinessOrFail** was not able to wait for an application to be in a ready state but just in a running state.  Unfortunately a pod not ready is running. 
Ready means that the Pod is running and the ready probe was used and is ok.
for Kubernetes:
Use isReady from the replicationController to ensure that the application is ready.
for Openshift:
Use isReady from the deploymentConfigs to ensure that the application is ready.
I have updated **awaitPodReadinessOrFail** on Pod to filter by using Readiness::isPodReady instead of running state.
Regarding testing, I can only make them on OpenShift. I have updated it **HelloWorldOpenShiftAssistantIT** to ensure that all pods (2) in the test are ready.
=> fix(#1051): improve waiting feature on application readiness

docs/kubernetes.adoc, openshift/api/src/main/java/org/arquillian/cube/openshift/api/OpenShiftDynamicImageStreamResource.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/resources/OpenShiftResourceFactory.java, openshift/openshift/src/test/java/org/arquillian/cube/openshift/impl/resources/OpenShiftResourceFactoryTest.java
It is now possible to use the `@OpenShiftDynamicImageStreamResource`
annotation to generate an image stream. This image stream will be added
to the freshly generated project and removed afterwards.
This makes it easy to specify which images should be used for the test.
Issue with testing OpenShift images is that we need to be able to specify which image should be tested. If you put tests in a pipeline you don't know what the image will be, but once it is executed, we know that information.
By definition tests should self-contained and prepare everything that is required to run the test. This includes image streams too IMHO. This is why generating an image stream beforehand and deploying it outside of the test is not really the way to go.
We can generate the image stream definition and it …
=> Make it possible to generate image streams

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/commons-v2.yml, docker/docker/src/test/resources/extends-docker-compose-env-v2.yml, docker/docker/src/test/resources/extends-docker-compose-v2.yml
Allows docker-compose `extend` with `version: "2"`.
- Use `DockerCompseConverter` in `ContainerBuilder#extend()`
Fixes #1069
=> Issue 1069

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverter.java
If Docker Compose is v3 it uses v2 logic instead of failing
- Compare by integer instead of by a string
Fixes #1084
=> fix(#1084): If Docker Compose is v3 it uses v2 logic instead of failing

docker/drone/src/main/java/org/arquillian/cube/docker/drone/CubeDroneConfiguration.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/VideoConversionLifecycleManager.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/VncRecorderLifecycleManager.java, docker/drone/src/main/java/org/arquillian/cube/docker/drone/util/VolumeCreator.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/SeleniumContainersTest.java, docker/ftest-container-star-operator/pom.xml, docs/drone.adoc
Catch and log errors in `@Observes` methods, but do not fail the suite and allow cleanups - This should actually be the default for any `@Observes` method, as the CDI events are synchronous - A failure prevents other observers from running, such as cleanups etc.
Also, the Cube internal images might need to be pulled from a user specified docker registry. So this PR also adds and new "dockerRegistry" property - I did think about using the _docker_ qualifier, but using _cubedrone_ allows for a different registry if required (actually have a use case for this). 
- Added try/catch/log to `@Observes` methods in above classes
- VolumeCreator.java should use a better path
- Added "dockerRegistry" property & documentation
Fixes #1098
=> #1098 VideoConversionLifecycleManager & VncRecorderLifecycleManager

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverterTest.java, docker/docker/src/test/resources/simple-docker-compose-volumes.yml
Expands and normalizes binding paths specified in volumes
- Ensure the Win syntax "//DRIVE/" is used
- Expand relative paths for Docker-Java API
Fixes #1100
=> Fix #1100 Normalized paths

docker/docker/src/main/java/org/arquillian/cube/docker/impl/afterStart/AfterStartActionFactory.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/afterStart/CustomAfterStartActionInstantiator.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/AfterStartContainerObserver.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerExtension.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/AfterStart.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CustomAfterStartAction.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/DockerCompositions.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/afterStart/AfterStartActionTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/afterStart/CustomAfterStartActionImpl.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/AfterStartContainerObserverTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java, spi/src/main/java/org/arquillian/cube/spi/afterStart/AfterStartAction.java
I want to copy files and execute commands after a container started (similar to the before stop commands)
Implemented AfterStart observer similar to BeforeStopObserver
Fixes #
=> Execute commands after container start

core/src/test/java/org/arquillian/cube/impl/shrinkwrap/asset/CacheUrlAssetTest.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfiguration.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolver.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeSuiteLifecycleController.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/SystemPropertiesCubeSetter.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/Ping.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolverTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/CubeContainerObjectTestEnricherTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/containerobject/DockerContainerObjectBuilderTest.java, docker/drone/src/test/java/org/arquillian/cube/docker/graphene/location/CubeDockerCustomizableURLResourceProviderTest.java, docker/ftest-boot2docker/src/test/java/org/arquillian/cube/persistence/UserRepositoryTest.java, docker/ftest-docker-junit5/pom.xml, docker/ftest-system-properties/src/test/java/org/arquillian/cube/docker/systemproperties/SystemPropertiesJUnitRuleIT.java, docker/ftest/src/test/java/org/arquillian/cube/persistence/UserRepositoryTest.java, docker/junit5/pom.xml, docker/reporter/src/main/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironment.java, docker/reporter/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java, docker/reporter/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeVncDroneVideoTest.java, docs/enrichers.adoc, fabric8-maven-plugin-build/src/test/java/org/fabric8/maven/plugin/build/ResourceGeneratorBuilderIT.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/DefaultConfigurationTest.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/PodInjection.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/ReplicationControllerInjection.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/ServiceInjection.java, openshift/ftest/src/test/java/org/arquillian/cube/openshift/ftest/HelloPodDeploymentOpenShiftITCase.java, requirement-spi/src/main/java/org/arquillian/cube/remote/requirement/RequiresRemoteResource.java
Trivial cleanups
Fix tests on Win and allow filtering of tests that attempt to access remote resources (eg, blocked by a firewall).
- Flag tests with RequiresRemoteResource to enable filtering
- Remove unused imports
- Update junit5 version
- Log useful info and error conditions
Preparation of #1107 - Which is a much larger WIP PR for later
=> Fix test for Win & filter tests requiring remote resources

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/AfterStopContainerObserver.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerExtension.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/AfterStop.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/CubeContainer.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/DockerCompositions.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/AfterStopContainerObserverTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfigurationTest.java
Sometimes it is useful to get access to files/logs after the container is stopped.
- new AfterStopContainerObserver
- new afterStop configuration
Fixes #
=> Copy files/logs after the container is stopped

pom.xml
This PR fixes issue #1049 
In snakeyaml 1.20 the API of `BaseConstructor.constructScalar(ScalarNode)` changed to return a String. This broke binary compatibility. `arquillian-cube` at the moment cannot be used with snakeyaml versions 1.20 or newer. The actual change is really simple: just upgrade to 1.24, no changes in source are needed. Recompiling the code with the new dependency will make it work with the new version.
=> chore(deps): bumps snakeyaml to 1.24

docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java
The default wait-for-it script is easily invoked without a HOST, because internalIP easily resolves to empty string.
An example invocation which can never succeed because it's syntactically incorrect:
/tmp/wait-for-it.sh :8080 -s -- echo Service is Up
We can go an extra step, and make sure that a non-empty HOST is set. we may not default to a good value but at least it's one that sometimes works.
- if internalIP is empty, default to containerIP, if that one is also empty default to localhost
=> fix: avoid issuing invalid wait-for-it command

docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ContainerBuilder.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/DockerComposeConverter.java, docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/YamlUtil.java
This patch allows using the following syntax in docker-compose:
- Decimal value for version (e.g. version: '3.5')
- List for entrypoint (e.g. entrypoint: [], or entrypoint: [/bin/sh, -c, echo]
- Map for environment
=> feat: adds docker-compose support for environment maps

.circleci/config.yml, docker/docker/pom.xml, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeConfiguratorTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolverTest.java, docker/docker/src/test/java/org/arquillian/cube/docker/impl/requirement/DockerRequirementTest.java, docker/ftest-docker-junit5/src/test/java/org/arquillian/cube/docker/junit5/NetworkTest.java, docker/ftest-docker-junit5/src/test/java/org/arquillian/cube/docker/junit5/RedisTest.java, docker/pom.xml, kubernetes/ftest-kubernetes-assistant/src/test/java/org/arquillian/cube/kubernetes/assistant/HelloWorldKubernetesAssistantTest.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/requirement/KubernetesRequirement.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftRequirement.java
This is an initial try to fix #1255 with at least unit testing enabled.
- Changed the circleci build script to support the current builds. Also in hope to be a little more future proof if integration tests are added
- Most important fix for the builds is the addition of ``setup_remote_docker`` to allow some docker specific tests
- Tried to get rid of some side effects based on environment variables in some unit tests by using ``@ClassRule EnvironmentVariables``
- Commented out some ``@ExtendWith`` annotations in the prepared Junit5 tests since the extension had problems and the tests did not contain actual tests
- Added some missing ``@Category``s to tests
- Fixed a problem with the ``OpenshiftRequirement`` and ``KubernetesRequirement`` where an unconfigured url raised an unhandled …
=> Fixing CircleCI unit tests for JDK8 and Docker

.github/workflows/maven.yml, docker/docker/src/test/java/org/arquillian/cube/docker/impl/await/DockerHealthAwaitStrategyTest.java, kubernetes/ftest-kubernetes-assistant/src/test/java/org/arquillian/cube/kubernetes/assistant/HelloWorldKubernetesAssistantTest.java, kubernetes/ftest-kubernetes-assistant/src/test/resources/kubernetes.json, kubernetes/ftest-kubernetes-logs/pom.xml, kubernetes/ftest-kubernetes-reporter/pom.xml, kubernetes/ftest-kubernetes-resources/pom.xml, kubernetes/ftest-kubernetes-resources/src/test/resources/hello-world-2.yaml, kubernetes/ftest-kubernetes-resources/src/test/resources/hello-world.yaml, kubernetes/ftest-kubernetes/pom.xml, kubernetes/ftest-kubernetes/src/test/java/HelloWorldIT.java, kubernetes/ftest-kubernetes/src/test/resources/kubernetes.yaml, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/KubernetesAssistant.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/portforward/PortForwarder.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/requirement/KubernetesRequirement.java, kubernetes/kubernetes/src/test/java/org/arquillian/cube/kubernetes/impl/MockTest.java, openshift/ftest-oc-proxy/src/test/resources/openshift.json, openshift/ftest-openshift-assistant/src/test/resources/openshift.json, openshift/ftest-openshift-graphene/src/test/resources/openshift.json, openshift/ftest-openshift-resources-standalone/src/test/resources/hello-openshift.json, openshift/ftest-openshift-restassured/src/test/resources/openshift.json
Changes aim at resuming Arquillian Cube tests for Kubernetes integration.
- Fixing Kubernetes integration implementation
- Fixing test resources and tests
- Removing the CircleCI script which does nothing relevant to actual integration tests, and improving the GitHub actions script n order to run a matrix on the docker and kubernetes targets.
Fixes #1313
=> Resume K8s integration tests

.github/dependabot.yml
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
=> chore(deps): enable Dependabot v2'

core/pom.xml
Duplicates #1325 but using 1.27.1, since the one proposed by dependantbot is throwing a NoClassFound exception. 
See #1325 
- commons-compress from 1.19 to 1.27.1
Fixes https://github.com/arquillian/arquillian-cube/security/dependabot?q=package%3Aorg.apache.commons%3Acommons-compress+manifest%3Acore%2Fpom.xml+has%3Apatch
=> Bump commons-compress to 1.21, to fix security issues, and related commons-* dependencies to align with docker-java:3.4.0

README.adoc, docs/bom.adoc, docs/build-containers.adoc, docs/compose.adoc, docs/configuration.adoc, docs/cop.adoc, docs/drone.adoc, docs/enrichers.adoc, docs/example.adoc, docs/kubernetes.adoc, docs/parallel.adoc, docs/polyglot.adoc, docs/preliminaries.adoc, docs/reports.adoc, docs/requirements.adoc, docs/restassured.adoc, docs/what-is-this.adoc
SSIA
Documentation update
- Mainly removing the Boot2Docker and Docker-machine mentions
- Minor fixes here and there as they were spotted
Fixes #1344
=> Update documentation for 2.0.0 release

jkube-maven-plugin-build/src/test/resources/spring-boot/pom.xml, pom.xml
- Bump Arquillian Core dependencies, JBoss parent and align ShrinkWrap ones by adding the same versions as Arquillian Core to the _dependencyManagment_ section 
- ...
Fixes #1318
=> [issue-1318] - Bump Arquillian Core and related dependencies to latest

kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioClientAdapter.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/namespace/DefaultNamespaceService.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/OpenShiftClientCreator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/external/OpenshiftClientResourceProvider.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/enricher/internal/OpenshiftClientResourceProvider.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/install/OpenshiftResourceInstaller.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/locator/OpenshiftKubernetesResourceLocator.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/Openshift4Requirement.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftOlmRequirement.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftRequirement.java
SessionManager is using a deprecated call to `isAdaptable`. This can lead to some classpath issues with Fabtric8 Kubernetes Client adapters, so this PR is proposing to replace the call with the non deprecated `supports()` method
- SessionManager::start 
Resolves #1360
=> Fix SessionManager in order to use a supported way to determine whether the the client is a k8s or OpenShift one

kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioClientAdapter.java, kubernetes/istio/istio/src/main/java/org/arquillian/cube/istio/impl/IstioResourceList.java, kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/portforward/PortForwarder.java, kubernetes/reporter/pom.xml, pom.xml
SSIA
Here we're bumping the Fabric8 Kubernetes client to the latest GA version.
- Upgrade Fabric8 Kubernetes client to 7.1.0
Fixes #1368
=> Bump Fabric8 Kubernetes Client version to 7.1.0

.github/workflows/e2e-tests.yml, openshift/ftest-openshift-routeurl/src/test/java/org/arquillian/cube/openshift/routeurl/RouteInOtherNamespaceIT.java, openshift/ftest/src/test/java/org/arquillian/cube/openshift/ftest/HelloPodDeploymentOpenShiftITCase.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/GitServer.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/Openshift4Requirement.java, openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/OpenshiftOlmRequirement.java, requirement-spi/src/main/java/org/arquillian/cube/olm/impl/requirement/RequiresOlm.java, requirement-spi/src/main/java/org/arquillian/cube/openshift/impl/requirement/RequiresOpenshift4.java
Inspired by https://github.com/fabric8io/kubernetes-client/blob/main/.github/workflows/e2e-crc-okd-tests.yml, we are replacing `manusa/actions-setup-openshift@v1.1.5` with CRC + OKD to run tests on OpenShift and overcome the end of support for Ubuntu 20 by GitHub public runners. `manusa/actions-setup-openshift@v1.1.5` requires Ubuntu 20, as newer versions don't work.
This way we can also switch to OpenShift 4, a desired outcome as a bonus.
- Fix the e2e workflow script
- Fix previous `@Ignore` to add details and add a new one to skip a test which was anyway skipped since we missed OLM, and now because it takes too much time and resources on CRC
Fixes #1372
=> Using CRC to run e2e tests against OpenShift 4

docker/docker/src/main/java/org/arquillian/cube/docker/impl/util/OperatingSystem.java
Builds not working on Windows 11 since the OperatingSystem enumeration is missing.
- Just added Windows 11 as a new enumeration to OperatingSystem
Fixes #1393
=> [issue-1393] Adding Windows 11 to the OperatingSystem enumerations

docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java, docker/drone/src/test/java/org/arquillian/cube/docker/drone/SeleniumContainersTest.java
Docker drone does not work on Windows 11 using WSL2 and Docker Desktop. Will produce the following Exception:
```
java.lang.IllegalArgumentException: java.nio.file.NoSuchFileException: target\vnc\.tmp1755861477422\screen.flv
at org.arquillian.cube.docker.drone.VncRecorderLifecycleManager.moveFromVolumeFolderToBuildDirectory(VncRecorderLifecycleManager.java:111)
```
Problem seems to be in the `richnorth/vnc-recorder` image.
- Change the used image to an updated version by another maintainer. Namely: testcontainers/vnc-recorder
Fixes #1395
=> [issue-1395] Fixing problems with running docker drone using Windows 11

docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/containerobject/dsl/ContainerBuilder.java, docker/ftest-docker-containerobject-dsl/src/test/java/org/arquillian/cube/containerobject/dsl/PostgreSqlIT.java, docker/ftest-docker-junit-rule/pom.xml, docker/ftest-docker-junit-rule/src/test/java/org/arquillian/cube/docker/junit/rule/PostgreSqlIT.java, docker/junit-rule/src/main/java/org/arquillian/cube/docker/junit/rule/ContainerDslRule.java, docker/junit5/src/main/java/org/arquillian/cube/docker/junit5/ContainerDsl.java
Changes allow to set a free form bind mount configuration option when creating a docker container so that - for example - `:Z` can be set for container that run on SELinux.
- Adding an overloaded version of `withVolume(String, String, String)` to ContainerBuilder, ContainerDsl and ContainerDslRule to allow setting free form option for volume mounts.
Fixes #1397
=> [issue 1397] - Adding support to mount volumes with free string configuration option
